#################################################################
#                                                               #
#                     Packages/Smoke Detectors                  #
#                                                               #
#################################################################


#################################################################
#                                                               #
#                       Nest                                    #
#                                                               #
#################################################################

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret


#################################################################
#                                                               #
#                       Binary Sensors                          #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#                Binary Sensor - Nest Protect      #
#                                                  #
####################################################

- platform: template
  sensors:
    nest_system:
      value_template: "{{ is_state('binary_sensor.hallway_nest_protect_online', 'on') and is_state('binary_sensor.back_hall_nest_protect_online', 'on') and is_state('binary_sensor.laundry_nest_protect_online', 'on') }}"
      friendly_name: 'Nest Protects'
      device_class: connectivity
      icon_template: mdi:smoke-detector
    nest_smoke:
      value_template: "{{ is_state('sensor.back_hall_nest_protect_smoke_status', 'Ok') and is_state('sensor.front_hall_nest_smoke_status', 'Ok') and is_state('sensor.laundry_nest_protect_smoke_status', 'Ok')}}"
      friendly_name: 'Nest Protects Smoke'
      device_class: smoke
      #icon_template: mdi:smoke-detector
    nest_co:
      value_template: "{{ is_state('sensor.back_hall_nest_protect_co_status', 'Ok') and is_state('sensor.front_hall_nest_co_status', 'Ok') and is_state('sensor.laundry_nest_protect_co_status', 'Ok')}}"
      friendly_name: 'Nest Protects CO'
      device_class: safety

  