#################################################################
#                                                               #
#                     Packages/Doors                            #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

group:
  doors_e:
    name: Door Entities
    entities:
      - input_boolean.fdoor
      - input_boolean.gdoor
      - binary_sensor.front_door_state_contact
      - binary_sensor.back_door_state_contact
      - binary_sensor.fdoor_lock
      - binary_sensor.fdoor_unlock
      - binary_sensor.fdoor_close
      - binary_sensor.fdoor_open
      - binary_sensor.bdoor_close
      - binary_sensor.bdoor_open
      - binary_sensor.gdoor_lock
      - binary_sensor.gdoor_unlock

      - binary_sensor.fdoor_door
      - binary_sensor.bdoor_door
      - binary_sensor.fdoor
      - binary_sensor.gdoor
      #smartthings
      - binary_sensor.back_door_state_acceleration
      - binary_sensor.front_door_state_acceleration
      # not used
      - sensor.front_door_state_z_coordinate
      - sensor.front_door_state_x_coordinate
      - sensor.front_door_state_y_coordinate
      - sensor.back_door_state_z_coordinate
      - sensor.back_door_state_x_coordinate
      - sensor.back_door_state_y_coordinate

#################################################################
#                                                               #
#                            Input Boolean                      #
#                                                               #
#################################################################

input_boolean:

####################################################
#                                                  #
#                Front & Garage Entry doors        #
#                                                  #
####################################################

  fdoor:
      name: Front Door
      icon: mdi:key-variant

  gdoor:
      name: Garage Entry
      icon: mdi:key-variant
      
#################################################################
#                                                               #
#                            Binary Sensor                      #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#                Front & Garage Entry doors        #
#                                                  #
####################################################

  - platform: template
    sensors:
      fdoor_close:
        friendly_name: FD Closed
        value_template: "{{ is_state('binary_sensor.front_door_state_contact', 'off') }}"
        icon_template: mdi:door
        device_class: connectivity
      fdoor_open:
        friendly_name: FD Open
        value_template: "{{ is_state('binary_sensor.front_door_state_contact', 'on') }}"
        icon_template: mdi:door-open
        device_class: door
      bdoor_close:
        friendly_name: BD Closed
        value_template: "{{ is_state('binary_sensor.back_door_state_contact', 'off') }}"
        icon_template: mdi:door-sliding
        device_class: connectivity
      bdoor_open:
        friendly_name: BD Open
        value_template: "{{ is_state('binary_sensor.back_door_state_contact', 'on') }}"
        icon_template: mdi:door-sliding-open
        device_class: door
      gdoor_close:
        friendly_name: GE Closed
        value_template: "{{ is_state('binary_sensor.gdoor_door', 'off') }}"
        icon_template: mdi:door
        device_class: connectivity
      gdoor_open:
        friendly_name: GE Open
        value_template: "{{ is_state('binary_sensor.gdoor_door', 'on') }}"
        icon_template: mdi:door-open
        device_class: door

####################################################
#                                                  #
#                Front & Garage Entry doors        #
#                                                  #
####################################################

  - platform: template
    sensors:
    #physical doors
      fdoor_door:
        value_template: "{{ is_state('binary_sensor.front_door_state_contact', 'on') }}"
        friendly_name: 'Front Door'
        device_class: door
        icon_template: mdi:door-open
      bdoor_door:  
        value_template: "{{ is_state('binary_sensor.back_door_state_contact', 'on') }}"
        friendly_name: 'Back Sliding Door'
        device_class: door
        icon_template: mdi:door-open
      gdoor_door:
        value_template: "{{ is_state('binary_sensor.garage_entry_door_iaszone', 'on') }}"
        friendly_name: 'Garage Entry'
        device_class: door
        icon_template: mdi:door-open

####################################################
#                                                  #
#                Invert Garage Entry door       #
#                                                  #
####################################################

lock:
  - platform: template
    name: Garage Entry Door
    value_template: "{{ is_state('lock.garage_entry_lock_doorlock', 'off') }}"
    lock:
      service: lock.unlock
      data:
        entity_id: lock.garage_entry_lock_doorlock
    unlock:
      service: lock.lock
      data:
        entity_id: lock.garage_entry_lock_doorlock
    #icon_template: "{% if is_state('lock.garage_entry_lock_doorlock', 'on') %}mdi:lock{% else %}mdi:lock-open{% endif %}"