###########################################################################
#
# Home Assistant Configuration v2
# 
# Main Configuration
#
###########################################################################

homeassistant:
#  name: !secret HA_NAME
#  latitude: !secret HA_LAT
#  longitude: !secret HA_LONG
#  elevation: !secret HA_ELE
#  unit_system: metric
#  #temperature_unit: C
#  time_zone: !secret HA_TZ
#  external_url: https://thompson-hq.duckdns.org
  packages: !include_dir_named packages
  customize: !include customize.yaml

###########################################################################
# 
# Standard Configuration
#
###########################################################################

# uncomment when using SSL
http:
  #base_url: !secret HA_URL
  #ssl_certificate: /ssl/fullchain.pem
  #ssl_key: /ssl/privkey.pem
  #ip_ban_enabled: true
  #login_attempts_threshold: 5

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Enables configuration UI
config:

# Checks for available updates
updater:

# Enables the frontend
frontend:
  #themes: !include themes.yaml
  themes: !include_dir_merge_named ./themes

lovelace:
#  mode: yaml

# Discover some devices automatically
discovery:
ssdp:
zeroconf:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# database controls
recorder:
  purge_keep_days: 5
  db_url: !secret maria_db_str

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# shopping !include_dir_list 
shopping_list:

# Enables a map showing the location of tracked devices
map:

# show system health information on info panel
system_health:

logger:
  default: warning
  #logs:
  #  homeassistant.components.smartthings: debug

###########################################################################
# 
# Custom Card/Component Configuration
#
###########################################################################

#lock:
#  - platform: Kevo
#    email: !secret kevo_email         # Your Kevo account Email
#    password: !secret kevo_pass       # Your Kevo account Password
#    lock_id: !secret kevo_id_f        # Your Kevo lock id (obtained manually from kevo website*)
#    max_retries: 3                    # Optionally set how many times it should try to initalise the lock
#    retry_delay: 2                    # Optionally set the delay (in seconds) between each retry


breaking_changes:

###########################################################################
# 
# Setup Configuration
#
###########################################################################

group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
