###########################################################################
#
# Home Assistant Configuration v2
# 
# Main Configuration
#
###########################################################################

homeassistant:
  name: !secret HA_NAME
  latitude: !secret HA_LAT
  longitude: !secret HA_LONG
  elevation: !secret HA_ELE
  unit_system: metric
  temperature_unit: C
  time_zone: !secret HA_TZ
  packages: !include_dir_named packages
  customize: !include customize.yaml

###########################################################################
# 
# Standard Configuration
#
###########################################################################

# uncomment when using SSL
http:
   base_url: !secret HA_URL
   ssl_certificate: /ssl/fullchain.pem
   ssl_key: /ssl/privkey.pem
   ip_ban_enabled: true
   login_attempts_threshold: 5

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Enables configuration UI
config:

# Checks for available updates
updater:

# Enables the frontend
frontend:
  themes: !include themes.yaml

lovelace:
  mode: yaml

# Discover some devices automatically
discovery:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# database controls
recorder:
  purge_keep_days: 5
  purge_interval: 1

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# show system health information on info panel
system_health:

logger:
  default: warning
  #logs:
  #  homeassistant.components.smartthings: debug

###########################################################################
# 
# Custom Card/Component Configuration
#
###########################################################################

# enables custom card updating & tracking
custom_updater:
  #mode: yaml
  hide_sensor: false
  show_installable: true
  track:
    - cards
    - components
    #- python scripts
  component_urls:
    - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json
  card_urls:
    - https://raw.githubusercontent.com/ljmerza/waze-card/master/updater.json
  #python_urls:
    #-

###########################################################################
# 
# Setup Configuration
#
###########################################################################




group: !include groups.yaml
script: !include scripts.yaml
