#################################################################
#                                                               #
#                     Packages/Hue Remotes                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

group:
  hue_remote_e:
    name: Hue Remote Entities
    view: no
    entities:
      - sensor.bedroom_remote
      - sensor.remote
      - binary_sensor.bathroom_motion_sensor
      - binary_sensor.ensuite_motion_sensor
      - binary_sensor.laundry_motion_sensor
      - binary_sensor.garage_motion_sensor

  hue_remote_a:
    name: Hue Remote Automations
    view: no
    entities:
      - automation.bed_remote_megan_lamp_toggle
      - automation.bed_remote_toggle_ensuite
      - automation.bed_remote_toggle_lightstrip
      - automation.bed_remote_simon_lamp_toggle
      - automation.bed_remote_set_night_all_off
      - automation.remote_set_evening
      - automation.remote_set_day
      - automation.remote_set_morning
      - automation.remote_set_night
      - automation.remote_set_night_all_off
      
#################################################################
#                                                               #
#                for the custom component to work               #
#                                                               #
#################################################################

hue:
  bridges:
    - host: 192.168.1.23
      allow_unreachable: true
      allow_hue_groups: true

#################################################################
#                                                               #
#                      Binary Sensor                            #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#             custom component                     #
#                                                  #
####################################################   

  - platform: huesensor

#################################################################
#                                                               #
#                       Sensor                                  #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#            sensor - custom component             #
#                                                  #
####################################################   

  - platform: huesensor

#################################################################
#                                                               #
#                       Device Tracker                          #
#                                                               #
#################################################################

device_tracker:

####################################################
#                                                  #
#            custom component                      #
#                                                  #
####################################################   

  - platform: huesensor

#################################################################
#                                                               #
#                       Automation                              #
#                                                               #
#################################################################

automation:

####################################################
#                                                  #
#            automation -  bedroom                 #
#                                                  #
#################################################### 

  - alias: bed_remote_megan_lamp_toggle
    trigger:
      - platform: state
        entity_id: sensor.bedroom_remote
        to: '1_click'
    action:
      - service: light.toggle
        entity_id: light.master_lightstrip
      
  - alias: bed_remote_toggle_ensuite
    trigger:
      - platform: state
        entity_id: sensor.bedroom_remote
        to: '2_click'
    action:
      - service: light.toggle
        entity_id: light.ensuite_3
        
  - alias: bed_remote_toggle_lightstrip
    trigger:
      - platform: state
        entity_id: sensor.bedroom_remote
        to: '3_click'
    action:
      - service: light.toggle
        entity_id: light.master_lightstrip
        
  - alias: bed_remote_simon_lamp_toggle
    trigger:
      - platform: state
        entity_id: sensor.bedroom_remote
        to: '4_click'
    action:
      - service: light.toggle
        entity_id: light.master_lightstrip

  ###################################
  ##
  ##  remote control - long press
  ## 
  ###################################

  # long press night time - shut down lights & tv etc.
  - alias: bed_remote_set_night_all_off
    trigger:
      - platform: state
        entity_id: sensor.bedroom_remote
        to: '2_hold'
    action:
      - service: homeassistant.turn_off
        entity_id: 
          - group.family_lights
          - light.master_lightstrip
          - light.ensuite_3
          - remote.harmony_hub
      - service: homeassistant.turn_on
        entity_id: 
          - input_boolean.fdoor
      - delay: '00:00:10'
      - service: homeassistant.turn_off
        entity_id: 
          - switch.dining_room_iron
          - switch.study_printer
          - switch.lounge_tv
          - switch.lounge_chairs

####################################################
#                                                  #
#            automation -  Living                  #
#                                                  #
#################################################### 

  - alias: remote_set_evening
    trigger:
      - platform: state
        entity_id: sensor.remote
        to: '1_click'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.time_mode
          option: '{{"Evening"}}'

  - alias: remote_set_day
    trigger:
      - platform: state
        entity_id: sensor.remote
        to: '2_click'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.time_mode
          option: '{{"Day"}}'

  - alias: remote_set_morning
    trigger:
      - platform: state
        entity_id: sensor.remote
        to: '3_click'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.time_mode
          option: '{{"Morning"}}'

  - alias: remote_set_night
    trigger:
      - platform: state
        entity_id: sensor.remote
        to: '4_click'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.time_mode
          option: '{{"Night"}}'

  ###################################
  ##
  ##  remote control - long press
  ## 
  ###################################

  # long press night time - shut down lights & tv etc.
  - alias: remote_set_night_all_off
    trigger:
      - platform: state
        entity_id: sensor.remote
        to: '4_hold'
    action:
      - service: homeassistant.turn_off
        entity_id: 
          - group.family_lights
          - remote.harmony_hub
      - service: homeassistant.turn_on
        entity_id: 
          - input_boolean.fdoor
      - delay: '00:00:10'
      - service: homeassistant.turn_off
        entity_id: 
          - switch.dining_room_iron
          - switch.study_printer
          - switch.lounge_tv
          - switch.lounge_chairs




  