#################################################################
#                                                               #
#                     Packages/Bus Times                        #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

group:
  bus_times_e:
    name: Bus Time Entities
    view: no
    entities:
      - sensor.home_to_tugg_79_ej
      - sensor.home_to_tugg_79_is
      - sensor.home_to_tugg_78_is
      - sensor.home_to_city_r5_out
      - sensor.tugg_to_city_r4
      - sensor.tugg_to_home_79
      - sensor.woden_to_home_R5
      - sensor.woden_to_tugg_R4
      - sensor.home_to_tugg_79_ej_format
      - sensor.home_to_tugg_79_is_format
      - sensor.home_to_tugg_78_is_format
      - sensor.home_to_city_r5_out_format
      - sensor.tugg_to_city_r4_format
      - sensor.woden_to_tugg_r4_homecheck
      - sensor.tugg_to_home_79_homecheck
      - sensor.woden_to_home_r5_homecheck
      
#################################################################
#                                                               #
#                       Sensors                                 #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                Sensor - routes to watch          #
#                                                  #
####################################################
  
  - platform: gtfs
    name: home_to_tugg_79_ej
    offset: 300 # 5min
    origin: 1075 #e&j
    destination: 13 #tugg arr
    scan_interval: 60 #1min
    data: action.zip

  - platform: gtfs
    name: home_to_tugg_79_is
    offset: 600 # 10min
    origin: 1007 #isashops far
    destination: 13 #tugg arr
    scan_interval: 60 #1min
    data: action.zip

  # 78 to tugg
  - platform: gtfs
    name: home_to_tugg_78_is
    offset: 600 # 10min
    origin: 1008 #isashops near
    destination: 13 #tugg arr
    scan_interval: 60 #1min
    data: action.zip

  # R5 north
  - platform: gtfs
    name: home_to_city_r5_out
    offset: 600 # 10min
    origin: 1078 #outrim near
    destination: 2710 #woden pt7 north
    scan_interval: 60 #1min
    data: action.zip

  # R4 north
  - platform: gtfs
    name: tugg_to_city_r4
    offset: 1200 # 20min
    origin: 1808 #tugg pt8
    destination: 2709 #woden north
    scan_interval: 60 #1min
    data: action.zip

  # 79 home with delay for Woden (18min)
  - platform: gtfs
    name: tugg_to_home_79
    offset: 1080 # 18min
    origin: 1803 #tugg pt3
    destination: 1076 #home e&j
    scan_interval: 60 #1min
    data: action.zip

  # R5 home with no delay from Woden
  - platform: gtfs
    name: woden_to_home_R5
    offset: 60 # 1min
    origin: 2705 #woden pt3
    destination: 1077 #home out
    scan_interval: 60 #1min
    data: action.zip

  # R4 tugg with no delay from Woden
  - platform: gtfs
    name: woden_to_tugg_R4
    offset: 60 # 1min
    origin: 2706 #woden pt6
    destination: 13 #tugg
    scan_interval: 60 #1min
    data: action.zip

####################################################
#                                                  #
#                Sensor - stopes to watch          #
#                                                  #
####################################################

  - platform: template
    sensors:
      #bus 1
      home_to_tugg_79_ej_format:
        friendly_name: Ell & Johnson (T) - 79
        icon_template: mdi:bus
        value_template: >-
          {% set departure = state_attr('sensor.home_to_tugg_79_ej', 'origin_stop_departure_time') %}
          {% if departure != None %}
            {% set route = state_attr('sensor.home_to_tugg_79_ej', 'route_route_short_name') %}
            {% set departure = departure.split(' ') %}
            {% set hms = departure[1].split(':') %}
            {{ route }} at {{hms[0]}}:{{hms[1]}}
          {% else %}
            unknown
          {% endif %}
      home_to_tugg_79_is_format:
        friendly_name: Isa School - 79
        icon_template: mdi:bus
        value_template: >-
          {% set departure = state_attr('sensor.home_to_tugg_79_is', 'origin_stop_departure_time') %}
          {% if departure != None %}
            {% set route = state_attr('sensor.home_to_tugg_79_is', 'route_route_short_name') %}
            {% set departure = departure.split(' ') %}
            {% set hms = departure[1].split(':') %}
            {{ route }} at {{hms[0]}}:{{hms[1]}}
          {% else %}
            unknown
          {% endif %}
      

      # home_to_tugg_78_is
      home_to_tugg_78_is_format:
        friendly_name: Isa Shops - 78
        icon_template: mdi:bus
        value_template: >-
          {% set departure = state_attr('sensor.home_to_tugg_78_is', 'origin_stop_departure_time') %}
          {% if departure != None %}
            {% set route = state_attr('sensor.home_to_tugg_78_is', 'route_route_short_name') %}
            {% set departure = departure.split(' ') %}
            {% set hms = departure[1].split(':') %}
            {{ route }} at {{hms[0]}}:{{hms[1]}}
          {% else %}
            unknown
          {% endif %}
        
      # home_to_city_r5_out
      home_to_city_r5_out_format:
        friendly_name: Outtrim Av - R5
        icon_template: mdi:bus
        value_template: >-
          {% set departure = state_attr('sensor.home_to_city_r5_out', 'origin_stop_departure_time') %}
          {% if departure != None %}
            {% set route = state_attr('sensor.home_to_city_r5_out', 'route_route_short_name') %}
            {% set departure = departure.split(' ') %}
            {% set hms = departure[1].split(':') %}
            {{ route }} at {{hms[0]}}:{{hms[1]}}
          {% else %}
            unknown
          {% endif %}
       
      # tugg_to_city_r4
      tugg_to_city_r4_format:
        friendly_name: Tugg pt8 - R4
        icon_template: mdi:bus
        value_template: >-
          {% set departure = state_attr('sensor.tugg_to_city_r4', 'origin_stop_departure_time') %}
          {% if departure != None %}
            {% set route = state_attr('sensor.tugg_to_city_r4', 'route_route_short_name') %}
            {% set departure = departure.split(' ') %}
            {% set hms = departure[1].split(':') %}
            {{ route }} at {{hms[0]}}:{{hms[1]}}
          {% else %}
            unknown
          {% endif %}

      # woden_to_tugg without delay
      woden_to_tugg_r4_homecheck:
        friendly_name: Woden pt6 - R4(T)
        icon_template: mdi:bus
        value_template: >-
          {% set departure = state_attr('sensor.woden_to_tugg_R4', 'origin_stop_departure_time') %}
          {% set arrival = state_attr('sensor.woden_to_tugg_R4', 'destination_stop_arrival_time') %}
          {% if departure != None %}
            {% set route = state_attr('sensor.woden_to_tugg_R4', 'route_route_short_name') %}
            {% set departure = departure.split(' ') %}
            {% set arrival = arrival.split(' ') %}
            {% set hms = departure[1].split(':') %}
            {% set ahms = arrival[1].split(':') %}
            Dep {{hms[0]}}:{{hms[1]}}, Tugg by {{ahms[0]}}:{{ahms[1]}}
          {% else %}
            unknown
          {% endif %}


      # tugg_to_home with delay
      tugg_to_home_79_homecheck:
        friendly_name: Tugg pt3 - 79
        icon_template: mdi:bus
        value_template: >-
          {% set departure = state_attr('sensor.tugg_to_home_79', 'origin_stop_departure_time') %}
          {% set arrival = state_attr('sensor.tugg_to_home_79', 'destination_stop_arrival_time') %}
          {% if departure != None %}
            {% set route = state_attr('sensor.tugg_to_home_79', 'route_route_short_name') %}
            {% set departure = departure.split(' ') %}
            {% set arrival = arrival.split(' ') %}
            {% set hms = departure[1].split(':') %}
            {% set ahms = arrival[1].split(':') %}
            Dep {{hms[0]}}:{{hms[1]}}, Home by {{ahms[0]}}:{{ahms[1]}}
          {% else %}
            unknown
          {% endif %}

      # woden_to_home_R5 with delay
      woden_to_home_r5_homecheck:
        friendly_name: Woden pt6 - R5(H)
        icon_template: mdi:bus
        value_template: >-
          {% set departure = state_attr('sensor.woden_to_home_R5', 'origin_stop_departure_time') %}
          {% set arrival = state_attr('sensor.woden_to_home_R5', 'destination_stop_arrival_time') %}
          {% if departure != None %}
            {% set route = state_attr('sensor.woden_to_home_R5', 'route_route_short_name') %}
            {% set departure = departure.split(' ') %}
            {% set arrival = arrival.split(' ') %}
            {% set hms = departure[1].split(':') %}
            {% set ahms = arrival[1].split(':') %}
            Dep {{hms[0]}}:{{hms[1]}}, Home by {{ahms[0]}}:{{ahms[1]}}
          {% else %}
            unknown
          {% endif %}


