#################################################################
#                                                               #
#                     Packages/Bus Times                        #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

group:
  bus_times_e:
    name: Bus Time Entities
    entities:
      - sensor.home_to_tugg_79_ej
      - sensor.home_to_tugg_79_is
      - sensor.home_to_tugg_78_is
      - sensor.home_to_city_r5_out
      - sensor.tugg_to_city_r4
      - sensor.tugg_to_home_79
      - sensor.woden_to_home_R5
      - sensor.woden_to_tugg_R4
      - sensor.home_to_tugg_79_ej_format
      - sensor.home_to_tugg_79_is_format
      - sensor.home_to_tugg_78_is_format
      - sensor.home_to_city_r5_out_format
      - sensor.tugg_to_city_r4_format
      - sensor.woden_to_tugg_r4_homecheck
      - sensor.tugg_to_home_79_homecheck
      - sensor.woden_to_home_r5_homecheck
      - input_boolean.clean_gtfs

#################################################################
#                                                               #
#                       Input Boolean                           #
#                                                               #
#################################################################

input_boolean:

####################################################
#                                                  #
#                flag to clean up new database     #
#                                                  #
####################################################

  clean_gtfs:
    name: Clean up new GTFS Database
    initial: off
    icon: mdi:bus-clock

#################################################################
#                                                               #
#                       Sensors                                 #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                Sensor - routes to watch          #
#                                                  #
####################################################

######################################
# Home 
######################################

  # home 79 to tugg
  - platform: gtfs
    name: home_to_tugg_79_ej
    offset: 300 # 5min
    origin: 1075 #e&j
    destination: 13 #tugg arr
    scan_interval: 60 #1min
    data: action.zip
    include_tomorrow: true
  
  # home R5 to woden
  - platform: gtfs
    name: home_to_city_r5_out
    offset: 600 # 10min
    origin: 1078 #outrim near
    destination: 2763 #woden 3 - temp interchange
    scan_interval: 60 #1min
    data: action.zip
    include_tomorrow: true

######################################
# Tugg 
######################################

  # tugg R4 to woden
  - platform: gtfs
    name: tugg_to_city_r4
    offset: 1200 # 20min
    origin: 1808 #tugg pt8
    destination: 2763 #woden 3 - temporary interchange
    scan_interval: 60 #1min
    data: action.zip
    include_tomorrow: true

  # tugg 79 to home with delay from Woden (18min)
  - platform: gtfs
    name: tugg_to_home_79
    offset: 1080 # 18min
    origin: 1803 #tugg pt3
    destination: 1076 #home e&j
    scan_interval: 60 #1min
    data: action.zip
    include_tomorrow: true

  # tugg 79 to home with no delay
  - platform: gtfs
    name: tugg_to_home_79_now
    offset: 60 # 1min
    origin: 1803 #tugg pt3
    destination: 1076 #home e&j
    scan_interval: 60 #1min
    data: action.zip
    include_tomorrow: true

######################################
# Woden 
######################################

  # woden to R5 home with no delay
  - platform: gtfs
    name: woden_to_home_R5
    offset: 0 # 0 sec
    origin: 2767 #woden pt4 - temp int
    destination: 1077 #home out
    scan_interval: 60 #1min
    data: action.zip
    include_tomorrow: true

  # woden to R4 tugg with no delay
  - platform: gtfs
    name: woden_to_tugg_R4
    offset: 0 # 0 sec
    origin: 2767 #woden pt4 - temp int
    destination: 13 #tugg
    scan_interval: 60 #1min
    data: action.zip
    include_tomorrow: true

######################################
# City 
######################################

  # City to UC (2,3,4)
  - platform: gtfs
    name: city_to_uc_rx
    offset: 60 # 1min
    origin: 3419 #city pt1
    destination: 4972 #uc
    scan_interval: 60 #1min
    data: action.zip
    include_tomorrow: true

# R4 south ANU to Woden
  - platform: gtfs
    name: anu_to_woden_r4r5
    offset: 300 # 5min
    origin: 4529 #anu->south
    destination: 2767 #woden plt4 - temp int
    scan_interval: 60 #1min
    data: action.zip
    include_tomorrow: true

# R4 south Assembly to Woden
  - platform: gtfs
    name: assembly_to_woden_r4
    offset: 300 # 5min
    origin: 3003 #assembly->south
    destination: 2767 #woden plt4 - temp int
    scan_interval: 60 #1min
    data: action.zip
    include_tomorrow: true


######################################
# UC/CIT 
######################################

  # UC to city (2,3,4) 10 min offset
  - platform: gtfs
    name: uc_to_city_rx
    offset: 360 # 10min
    origin: 4979 #uc 
    destination: 3418 #city
    scan_interval: 60 #1min
    data: action.zip
    include_tomorrow: true

  # UC Public Hospital to Bel(31)
  - platform: gtfs
    name: ucph_to_bel_31
    offset: 60 # 1min
    origin: 1737 #ucph 
    destination: 5517 #bel
    scan_interval: 60 #1min
    data: action.zip
    include_tomorrow: true

  # Bel to UC Public Hospital (31)
  - platform: gtfs
    name: bel_to_ucph_31
    offset: 60 # 1min
    origin: 5513 #bel pt
    destination: 1736 #uc
    scan_interval: 60 #1min
    data: action.zip
    include_tomorrow: true

####################################################
#                                                  #
#                Sensor - stops to watch          #
#                                                  #
####################################################

######################################
# Home 
######################################

  - platform: template
    sensors:
      #bus 1
      home_to_tugg_79_ej_format:
        friendly_name: Ell & Johnson (T) - 79
        icon_template: mdi:bus
        value_template: >-
          {% set departure = state_attr('sensor.home_to_tugg_79_ej', 'origin_stop_departure_time') %}
          {% if departure != None %}
            {% set route = state_attr('sensor.home_to_tugg_79_ej', 'route_route_short_name') %}
            {% set departure = departure.split(' ') %}
            {% set hms = departure[1].split(':') %}
            {{ route }} at {{hms[0]}}:{{hms[1]}}
          {% else %}
            unknown
          {% endif %}
              
      # home_to_city_r5_out
      home_to_city_r5_out_format:
        friendly_name: Outtrim Av - R5
        icon_template: mdi:bus
        value_template: >-
          {% set departure = state_attr('sensor.home_to_city_r5_out', 'origin_stop_departure_time') %}
          {% if departure != None %}
            {% set route = state_attr('sensor.home_to_city_r5_out', 'route_route_short_name') %}
            {% set departure = departure.split(' ') %}
            {% set hms = departure[1].split(':') %}
            {{ route }} at {{hms[0]}}:{{hms[1]}}
          {% else %}
            unknown
          {% endif %}

######################################
# Tugg 
######################################

      # tugg_to_home without delay
      tugg_to_home_79_format_now:
        friendly_name: Tugg pt3 - 79
        icon_template: mdi:bus
        value_template: >-
          {% set departure = state_attr('sensor.tugg_to_home_79_now', 'origin_stop_departure_time') %}
          {% if departure != None %}
            {% set route = state_attr('sensor.tugg_to_home_79_now', 'route_route_short_name') %}
            {% set departure = departure.split(' ') %}
            {% set hms = departure[1].split(':') %}
            {{ route }} at {{hms[0]}}:{{hms[1]}}
          {% else %}
            unknown
          {% endif %}

      # tugg_to_city_r4
      tugg_to_city_r4_format:
        friendly_name: Tugg pt8 - R4
        icon_template: mdi:bus
        value_template: >-
          {% set departure = state_attr('sensor.tugg_to_city_r4', 'origin_stop_departure_time') %}
          {% if departure != None %}
            {% set route = state_attr('sensor.tugg_to_city_r4', 'route_route_short_name') %}
            {% set departure = departure.split(' ') %}
            {% set hms = departure[1].split(':') %}
            {{ route }} at {{hms[0]}}:{{hms[1]}}
          {% else %}
            unknown
          {% endif %}

      # tugg_to_home with delay from woden
      tugg_to_home_79_homecheck:
        friendly_name: Tugg pt3 - 79 (Woden Delay)
        icon_template: mdi:bus
        value_template: >-
          {% set departure = state_attr('sensor.tugg_to_home_79', 'origin_stop_departure_time') %}
          {% set arrival = state_attr('sensor.tugg_to_home_79', 'destination_stop_arrival_time') %}
          {% if departure != None %}
            {% set route = state_attr('sensor.tugg_to_home_79', 'route_route_short_name') %}
            {% set departure = departure.split(' ') %}
            {% set arrival = arrival.split(' ') %}
            {% set hms = departure[1].split(':') %}
            {% set ahms = arrival[1].split(':') %}
            Dep {{hms[0]}}:{{hms[1]}}, Home by {{ahms[0]}}:{{ahms[1]}}
          {% else %}
            unknown
          {% endif %}

######################################
# Woden 
######################################

      # woden_to_tugg without delay
      woden_to_tugg_r4_homecheck:
        friendly_name: Woden pt4 - R4(T)
        icon_template: mdi:bus
        value_template: >-
          {% set departure = state_attr('sensor.woden_to_tugg_R4', 'origin_stop_departure_time') %}
          {% set arrival = state_attr('sensor.woden_to_tugg_R4', 'destination_stop_arrival_time') %}
          {% if departure != None %}
            {% set route = state_attr('sensor.woden_to_tugg_R4', 'route_route_short_name') %}
            {% set departure = departure.split(' ') %}
            {% set arrival = arrival.split(' ') %}
            {% set hms = departure[1].split(':') %}
            {% set ahms = arrival[1].split(':') %}
            Dep {{hms[0]}}:{{hms[1]}}, Tugg by {{ahms[0]}}:{{ahms[1]}}
          {% else %}
            unknown
          {% endif %}

      
      # woden_to_home_R5 without delay
      woden_to_home_r5_homecheck:
        friendly_name: Woden pt4 - R5(H)
        icon_template: mdi:bus
        value_template: >-
          {% set departure = state_attr('sensor.woden_to_home_R5', 'origin_stop_departure_time') %}
          {% set arrival = state_attr('sensor.woden_to_home_R5', 'destination_stop_arrival_time') %}
          {% if departure != None %}
            {% set route = state_attr('sensor.woden_to_home_R5', 'route_route_short_name') %}
            {% set departure = departure.split(' ') %}
            {% set arrival = arrival.split(' ') %}
            {% set hms = departure[1].split(':') %}
            {% set ahms = arrival[1].split(':') %}
            Dep {{hms[0]}}:{{hms[1]}}, Home by {{ahms[0]}}:{{ahms[1]}}
          {% else %}
            unknown
          {% endif %}

######################################
# City 
######################################

      # city_to_uc_rx
      city_to_uc_rx_format:
        friendly_name: City pt1 - RX(N) 
        icon_template: mdi:bus
        value_template: >-
          {% set departure = state_attr('sensor.city_to_uc_rx', 'origin_stop_departure_time') %}
          {% if departure != None %}
            {% set route = state_attr('sensor.city_to_uc_rx', 'route_route_short_name') %}
            {% set departure = departure.split(' ') %}
            {% set hms = departure[1].split(':') %}
            {{ route }} at {{hms[0]}}:{{hms[1]}}
          {% else %}
            unknown
          {% endif %}

      # anu_to_woden_r4
      anu_to_woden_r4_format:
        friendly_name: ANU - R4/R5(S) 
        icon_template: mdi:bus
        value_template: >-
          {% set departure = state_attr('sensor.anu_to_woden_r4r5', 'origin_stop_departure_time') %}
          {% if departure != None %}
            {% set route = state_attr('sensor.anu_to_woden_r4r5', 'route_route_short_name') %}
            {% set departure = departure.split(' ') %}
            {% set hms = departure[1].split(':') %}
            {{ route }} at {{hms[0]}}:{{hms[1]}}
          {% else %}
            unknown
          {% endif %}

      # assebemly_to_woden_r4
      ass_to_woden_r4_format:
        friendly_name: London - R4/R5(S) 
        icon_template: mdi:bus
        value_template: >-
          {% set departure = state_attr('sensor.assembly_to_woden_r4', 'origin_stop_departure_time') %}
          {% if departure != None %}
            {% set route = state_attr('sensor.assembly_to_woden_r4', 'route_route_short_name') %}
            {% set departure = departure.split(' ') %}
            {% set hms = departure[1].split(':') %}
            {{ route }} at {{hms[0]}}:{{hms[1]}}
          {% else %}
            unknown
          {% endif %}

######################################
# UC 
######################################

      # uc to city
      uc_to_city_rx_format:
        friendly_name: UC - RX(S) 
        icon_template: mdi:bus
        value_template: >-
          {% set departure = state_attr('sensor.uc_to_city_rx', 'origin_stop_departure_time') %}
          {% if departure != None %}
            {% set route = state_attr('sensor.uc_to_city_rx', 'route_route_short_name') %}
            {% set departure = departure.split(' ') %}
            {% set hms = departure[1].split(':') %}
            {{ route }} at {{hms[0]}}:{{hms[1]}}
          {% else %}
            unknown
          {% endif %}

      # 31 to bel
      ucph_to_bel_31_format:
        friendly_name: UCPH - 31(B) 
        icon_template: mdi:bus
        value_template: >-
          {% set departure = state_attr('sensor.ucph_to_bel_31', 'origin_stop_departure_time') %}
          {% if departure != None %}
            {% set route = state_attr('sensor.ucph_to_bel_31', 'route_route_short_name') %}
            {% set departure = departure.split(' ') %}
            {% set hms = departure[1].split(':') %}
            {{ route }} at {{hms[0]}}:{{hms[1]}}
          {% else %}
            unknown
          {% endif %}


