#################################################################
#                                                               #
#                     Packages/Fans                             #
#                                                               #
#################################################################


#################################################################
#                                                               #
#                       Binary Sensor                           #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#            binary Sensor - Interface              #
#                                                  #
#################################################### 

  - platform: template
    sensors:
      fans_off:
        friendly_name: Fans Off
        #value_template: "{{ is_state('input_select.master_fan_flag', 'Off') and is_state('input_select.staci_fan_flag', 'Off') and is_state('input_select.delia_fan_flag', 'Off')  }}"
        value_template: "{{ is_state('fan.master_fan_control_fan', 'off') and is_state('fan.staci_fan_control_fan', 'off') and is_state('fan.delia_fan_control_fan', 'off') and is_state('fan.lounge_fan_control_fan', 'off') and is_state('fan.study_fan_control_fan', 'off')  }}"
        icon_template: mdi:fan-off
        device_class: motion
      fans_on:
        friendly_name: Fans On
        value_template: "{{ is_state('binary_sensor.fans_off', 'off') }}"
        icon_template: mdi:fan

####################################################
#                                                  #
#            binary Sensor - Interface     dyson         #
#                                                  #
#################################################### 

  - platform: template
    sensors:
      purifier_off:
        friendly_name: Purifier Off
        value_template: "{{ is_state('climate.pure_hot_cool', 'off') and is_state('fan.pure_hot_cool', 'off') }}"
        icon_template: mdi:crosshairs-off
        device_class: motion
      purifier_on:
        friendly_name: Purifier On
        value_template: "{{ is_state('binary_sensor.purifier_off', 'off') }}"
        icon_template: mdi:air-filter

####################################################
#                                                  #
#            binary Sensor - Interface     tuya heaters         #
#                                                  #
#################################################### 

  - platform: template
    sensors:
      heaters_off:
        friendly_name: Heaters Off
        value_template: "{{ is_state('climate.heater_study', 'off') or is_state('climate.heater_study', 'unavailable') }}"
        icon_template: mdi:radiator-off
        device_class: motion
      heaters_on:
        friendly_name: Heaters On
        #value_template: "{{ is_state('climate.83607036e098068310e2', 'on') and is_state('climate.33805060a4cf12d11732', 'on') and is_state('climate.83607036e09806830fb8', 'on') }}"
        #value_template: "{{ not is_state('climate.heater_ensuite', 'off') and not is_state('climate.heater_study', 'off') }}"
        value_template: "{{ is_state('binary_sensor.heaters_off', 'off')   }}"
        icon_template: mdi:radiator