#################################################################
#                                                               #
#                     Packages/Fans                             #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

group:
  fans_e:
    name: Fan Entities
    view: no
    entities:
      - input_select.master_fan_flag
      - input_select.staci_fan_flag
      - input_select.delia_fan_flag
      - binary_sensor.fans_on
      - binary_sensor.fans_off
      - device_tracker.bond_hub

  fans_a:
    name: Fan Automations
    view: no
    entities:
      - script.fans_off
      - script.fans_on
      - automation.master_fan_off
      - automation.master_fan_1
      - automation.master_fan_2
      - automation.master_fan_3
      - automation.staci_fan_off
      - automation.staci_fan_1
      - automation.staci_fan_2
      - automation.staci_fan_3
      - automation.delia_fan_off
      - automation.delia_fan_1
      - automation.delia_fan_2
      - automation.delia_fan_3

#################################################################
#                                                               #
#                       Input Select                            #
#                                                               #
#################################################################

input_select:

####################################################
#                                                  #
#            input_select fans                     #
#                                                  #
#################################################### 

  master_fan_flag:
    name: Master Fan
    options:
      - 'Off'
      - '1'
      - '2'
      - '3'
      - 'Transition'
    icon: mdi:fan

  staci_fan_flag:
    name: Staci Fan
    options:
      - 'Off'
      - '1'
      - '2'
      - '3'
      - 'Transition'
    icon: mdi:fan

  delia_fan_flag:
    name: Delia Fan
    options:
      - 'Off'
      - '1'
      - '2'
      - '3'
      - 'Transition'
    icon: mdi:fan

#################################################################
#                                                               #
#                       Binary Sensor                           #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#            binary Sensor - Interface              #
#                                                  #
#################################################### 

  - platform: template
    sensors:
      fans_off:
        friendly_name: Fans Off
        value_template: "{{ is_state('input_select.master_fan_flag', 'Off') and is_state('input_select.staci_fan_flag', 'Off') and is_state('input_select.delia_fan_flag', 'Off')  }}"
        icon_template: mdi:fan-off
        device_class: motion
      fans_on:
        friendly_name: Fans On
        value_template: "{{ is_state('binary_sensor.fans_off', 'off') }}"
        icon_template: mdi:fan

#################################################################
#                                                               #
#                       Scripts                                 #
#                                                               #
#################################################################

script:

####################################################
#                                                  #
#            script - all fans on/off              #
#                                                  #
#################################################### 

  fans_off:
    sequence:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.master_fan_flag
          option: '{{"Transition"}}'
      - service: input_select.select_option
        data_template:
          entity_id: input_select.staci_fan_flag
          option: '{{"Transition"}}'
      - service: input_select.select_option
        data_template:
          entity_id: input_select.delia_fan_flag
          option: '{{"Transition"}}'
      - service: input_select.select_option
        data_template:
          entity_id: input_select.master_fan_flag
          option: '{{"Off"}}'
      - service: input_select.select_option
        data_template:
          entity_id: input_select.staci_fan_flag
          option: '{{"Off"}}'
      - service: input_select.select_option
        data_template:
          entity_id: input_select.delia_fan_flag
          option: '{{"Off"}}'
      
  fans_low:
    sequence:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.master_fan_flag
          option: '{{"Transition"}}'
      - service: input_select.select_option
        data_template:
          entity_id: input_select.staci_fan_flag
          option: '{{"Transition"}}'
      - service: input_select.select_option
        data_template:
          entity_id: input_select.delia_fan_flag
          option: '{{"Transition"}}'
      - service: input_select.select_option
        data_template:
          entity_id: input_select.master_fan_flag
          option: '{{"1"}}'
      - service: input_select.select_option
        data_template:
          entity_id: input_select.staci_fan_flag
          option: '{{"1"}}'
      - service: input_select.select_option
        data_template:
          entity_id: input_select.delia_fan_flag
          option: '{{"1"}}'

#################################################################
#                                                               #
#                       Automation                              #
#                                                               #
#################################################################

automation:

####################################################
#                                                  #
#            automation - ifttt triggers           #
#                                                  #
#################################################### 


  #################################
  ## Master
  #################################

  - alias: master_fan_off
    trigger:
      - platform: state
        entity_id: input_select.master_fan_flag
        to: 'Off'
    action:
      - service: ifttt.trigger
        data: {"event":"master_fan_off"}

  - alias: master_fan_1
    trigger:
      - platform: state
        entity_id: input_select.master_fan_flag
        to: '1'
    action:
      - service: ifttt.trigger
        data: {"event":"master_fan_1"}

  - alias: master_fan_2
    trigger:
      - platform: state
        entity_id: input_select.master_fan_flag
        to: '2'
    action:
      - service: ifttt.trigger
        data: {"event":"master_fan_2"}

  - alias: master_fan_3
    trigger:
      - platform: state
        entity_id: input_select.master_fan_flag
        to: '3'
    action:
      - service: ifttt.trigger
        data: {"event":"master_fan_3"}

  #################################
  ## Staci
  #################################

  - alias: staci_fan_off
    trigger:
      - platform: state
        entity_id: input_select.staci_fan_flag
        to: 'Off'
    action:
      - service: ifttt.trigger
        data: {"event":"master_fan_off"}

  - alias: staci_fan_1
    trigger:
      - platform: state
        entity_id: input_select.staci_fan_flag
        to: '1'
    action:
      - service: ifttt.trigger
        data: {"event":"master_fan_1"}

  - alias: staci_fan_2
    trigger:
      - platform: state
        entity_id: input_select.staci_fan_flag
        to: '2'
    action:
      - service: ifttt.trigger
        data: {"event":"master_fan_2"}

  - alias: staci_fan_3
    trigger:
      - platform: state
        entity_id: input_select.staci_fan_flag
        to: '3'
    action:
      - service: ifttt.trigger
        data: {"event":"staci_fan_3"}

  #################################
  ## Delia
  #################################

  - alias: delia_fan_off
    trigger:
      - platform: state
        entity_id: input_select.delia_fan_flag
        to: 'Off'
    action:
      - service: ifttt.trigger
        data: {"event":"delia_fan_off"}

  - alias: delia_fan_1
    trigger:
      - platform: state
        entity_id: input_select.delia_fan_flag
        to: '1'
    action:
      - service: ifttt.trigger
        data: {"event":"delia_fan_1"}

  - alias: delia_fan_2
    trigger:
      - platform: state
        entity_id: input_select.delia_fan_flag
        to: '2'
    action:
      - service: ifttt.trigger
        data: {"event":"delia_fan_2"}

  - alias: delia_fan_3
    trigger:
      - platform: state
        entity_id: input_select.delia_fan_flag
        to: '3'
    action:
      - service: ifttt.trigger
        data: {"event":"delia_fan_3"}