#################################################################
#                                                               #
#                     Packages/Fans                             #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

group:
  fans_e:
    name: Fan Entities
    entities:
      - input_select.master_fan_flag
      - input_select.staci_fan_flag
      - input_select.delia_fan_flag
      - binary_sensor.fans_on
      - binary_sensor.fans_off
      - device_tracker.bond_hub

  fans_a:
    name: Fan Automations
    entities:
      - script.fans_off
      - script.fans_on
      - automation.master_fan_off
      - automation.master_fan_1
      - automation.master_fan_2
      - automation.master_fan_3
      - automation.staci_fan_off
      - automation.staci_fan_1
      - automation.staci_fan_2
      - automation.staci_fan_3
      - automation.delia_fan_off
      - automation.delia_fan_1
      - automation.delia_fan_2
      - automation.delia_fan_3

################################################################
#                                                               #
#                       Dyson Integration                        #
#                                                               #
#################################################################

dyson:
  username: !secret dyson_user
  password: !secret dyson_pass
  language: AU
  devices:
    device_id: !secret dyson_dida
    device_ip: !secret dyson_dipa



#################################################################
#                                                               #
#                       Binary Sensor                           #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#            binary Sensor - Interface              #
#                                                  #
#################################################### 

  - platform: template
    sensors:
      fans_off:
        friendly_name: Fans Off
        #value_template: "{{ is_state('input_select.master_fan_flag', 'Off') and is_state('input_select.staci_fan_flag', 'Off') and is_state('input_select.delia_fan_flag', 'Off')  }}"
        value_template: "{{ is_state('fan.master_fan', 'off') and is_state('fan.staci_s_fan', 'off') and is_state('fan.delia_s_fan', 'off')  }}"
        icon_template: mdi:fan-off
        device_class: motion
      fans_on:
        friendly_name: Fans On
        value_template: "{{ is_state('binary_sensor.fans_off', 'off') }}"
        icon_template: mdi:fan

####################################################
#                                                  #
#            binary Sensor - Interface     dyson         #
#                                                  #
#################################################### 

  - platform: template
    sensors:
      purifier_off:
        friendly_name: Purifier Off
        value_template: "{{ is_state('fan.lounge', 'off') }}"
        icon_template: mdi:crosshairs-off
        device_class: motion
      purifier_on:
        friendly_name: Purifier On
        value_template: "{{ is_state('binary_sensor.purifier_off', 'off') }}"
        icon_template: mdi:air-filter

####################################################
#                                                  #
#            binary Sensor - Interface     tuya heaters         #
#                                                  #
#################################################### 

  - platform: template
    sensors:
      heaters_off:
        friendly_name: Heaters Off
        value_template: "{{ is_state('climate.83607036e098068310e2', 'off') and is_state('climate.33805060a4cf12d11732', 'off') and is_state('climate.83607036e09806830fb8', 'off') }}"
        icon_template: mdi:radiator-off
        device_class: motion
      heaters_on:
        friendly_name: Heaters On
        value_template: "{{ is_state('binary_sensor.purifier_off', 'off') }}"
        icon_template: mdi:radiator