#################################################################
#                                                               #
#                     Packages/Bed Warming                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

group:
  weather_e:
    name: Weather Entities
    entities:
      - sun.sun
      - sensor.season
      - weather.dark_sky
      - camera.bom_canberra_radar
      - sensor.inside_now
      - input_boolean.weather_storms
      # dam levels

  weather_bom_e:
    name: Weather BOM Entities
    entities:
      - sensor.bom_tuggeranong_isabella_plains_aws_air_temp_c
      - sensor.bom_tuggeranong_isabella_plains_aws_delta_temp_c
      - sensor.bom_tuggeranong_isabella_plains_aws_dew_point_c
      - sensor.bom_tuggeranong_isabella_plains_aws_feels_like_c
      - sensor.bom_tuggeranong_isabella_plains_aws_pressure_mb
      - sensor.bom_tuggeranong_isabella_plains_aws_pressure_msl
      - sensor.bom_tuggeranong_isabella_plains_aws_pressure_qnh
      - sensor.bom_tuggeranong_isabella_plains_aws_rain_today
      - sensor.bom_tuggeranong_isabella_plains_aws_relative_humidity
      - sensor.bom_tuggeranong_isabella_plains_aws_visability_km
      - sensor.bom_tuggeranong_isabella_plains_aws_wind_direction
      - sensor.bom_tuggeranong_isabella_plains_aws_wind_gust_kmh
      - sensor.bom_tuggeranong_isabella_plains_aws_wind_speed_kmh
      
  weather_dsky_e:
    name: Weather Dark Sky Entities
    entities:
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_cloud_coverage_0d
      - sensor.dark_sky_cloud_coverage_1d
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_daytime_high_temperature_0d
      - sensor.dark_sky_daytime_high_temperature_1d
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_humidity
      - sensor.dark_sky_humidity_0d
      - sensor.dark_sky_humidity_1d
      - sensor.dark_sky_icon
      - sensor.dark_sky_icon_0d
      - sensor.dark_sky_icon_1d
      - sensor.dark_sky_overnight_low_temperature_0d
      - sensor.dark_sky_overnight_low_temperature_1d
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_0d
      - sensor.dark_sky_precip_1d
      - sensor.dark_sky_precip_accumulation_0d
      - sensor.dark_sky_precip_accumulation_1d
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_intensity_0d
      - sensor.dark_sky_precip_intensity_1d
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_probability_0d
      - sensor.dark_sky_precip_probability_1d
      - sensor.dark_sky_pressure
      - sensor.dark_sky_pressure_0d
      - sensor.dark_sky_pressure_1d
      - sensor.dark_sky_summary
      - sensor.dark_sky_summary_0d
      - sensor.dark_sky_summary_1d
      - sensor.dark_sky_temperature
      - sensor.dark_sky_uv_index
      - sensor.dark_sky_uv_index_0d
      - sensor.dark_sky_uv_index_1d
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_bearing_0d
      - sensor.dark_sky_wind_bearing_1d
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_speed_0d
      - sensor.dark_sky_wind_speed_1d

  weather_dam_e:
    name: Weather Dam Entities
    entities:
      - input_boolean.check_dams
      - input_text.dam_act_catchment_total
      - input_text.dam_act_catchment_percent
      - input_text.dam_act_googong_total
      - input_text.dam_act_googong_percent
      - input_text.dam_act_cotter_total
      - input_text.dam_act_cotter_percent
      - input_text.dam_act_corin_total
      - input_text.dam_act_corin_percent
      - input_text.dam_act_bendora_total
      - input_text.dam_act_bendora_percent

#################################################################
#                                                               #
#                      Input Boolean                            #
#                                                               #
#################################################################

input_boolean:

####################################################
#                                                  #
#                weather storms                    #
#                                                  #
####################################################

  weather_storms:
    name: Lightning around home
    icon: mdi:weather-lightning

  weather_fires:
    name: Fires around home
    icon: mdi:fire

#  DAM_FLAG: "input_boolean.check_dams"
  check_dams:
    name: Check ACT Dam levels
    icon: mdi:cup-water

#################################################################
#                                                               #
#                            Input_text  for dams               #
#                                                               #
#################################################################

#input_text:

# #  CATCHMENT_T: "input_text.dam_act_catchment_total"
#   dam_act_catchment_total:
#     name: ACT Catchment Total
#     initial: '0'
# #  CATCHMENT_P: "input_text.dam_act_catchment_percent"
#   dam_act_catchment_percent:
#     name: ACT Catchment %
#     initial: '0'
# #  GOOGONG_T: "input_text.dam_act_googong_total"
#   dam_act_googong_total:
#     name: ACT Googong Total
#     initial: '0'
# #  GOOGONG_P: "input_text.dam_act_googong_percent"
#   dam_act_googong_percent:
#     name: ACT Googong %
#     initial: '0'
# #  COTTER_T: "input_text.dam_act_cotter_total"
#   dam_act_cotter_total:
#     name: ACT Cotter Total
#     initial: '0'
# #  COTTER_P: "input_text.dam_act_cotter_percent"
#   dam_act_cotter_percent:
#     name: ACT Cotter %
#     initial: '0'
# #  CORIN_T: "input_text.dam_act_corin_total"
#   dam_act_corin_total:
#     name: ACT Corin Total
#     initial: '0'
# #  CORIN_P: "input_text.dam_act_corin_percent"
#   dam_act_corin_percent:
#     name: ACT Corin %
#     initial: '0'
# #  BENDORA_T: "input_text.dam_act_bendora_total"
#   dam_act_bendora_total:
#     name: ACT Bendora Total
#     initial: '0'
# #  BENDORA_P: "input_text.dam_act_bendora_percent"
#   dam_act_bendora_percent:
#     name: ACT Bendora %
#     initial: '0'


#################################################################
#                                                               #
#                      Sun                                      #
#                                                               #
#################################################################

sun:

#################################################################
#                                                               #
#                      Weather                                  #
#                                                               #
#################################################################

weather:
  - platform: darksky
    api_key: !secret darksky_token

#################################################################
#                                                               #
#                      Lightning strikes                        #
#                                                               #
#################################################################

wwlln:
  radius: 50
  latitude: !secret HA_LAT
  longitude: !secret HA_LONG

#################################################################
#                                                               #
#                      NSW Bushfires                            #
#                                                               #
#################################################################

geo_location:
  - platform: nsw_rural_fire_service_feed

#################################################################
#                                                               #
#                      UV                                       #
#                                                               #
#################################################################

openuv:
  api_key: !secret uv_key
  #the below is no longer valid from 0.105.0
  # binary_sensors:
  #   monitored_conditions:
  #     - uv_protection_window
  # sensors:
  #   monitored_conditions:
  #     - current_ozone_level
  #     - current_uv_index
  #     - current_uv_level
  #     - max_uv_index
  #     - safe_exposure_time_type_1
  #     - safe_exposure_time_type_2
  #     - safe_exposure_time_type_3
  #     - safe_exposure_time_type_4
  #     - safe_exposure_time_type_5
  #     - safe_exposure_time_type_6


#################################################################
#                                                               #
#                      Sensors                                  #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                      Scrape    see appdaemon     #
#                                                  #
####################################################

  # - platform: scrape
  #   resource: https://www.eldersweather.com.au/dam-level/act/
  #   select: "td"
  #   name: ACT Dam Levels
  #   scan_interval: 259200
  #   # request every 3 days

####################################################
#                                                  #
#                Indoor Temp                       #
#                                                  #
####################################################

  - platform: template
    sensors:
      inside_now:
        friendly_name: Temp Inside
        value_template: "{{ states('sensor.back_door_state_temperature_measurement') }}"

####################################################
#                                                  #
#                Air Quality                       #
#                                                  #
####################################################

  - platform: airvisual
    api_key: !secret air_vis_key
    monitored_conditions:
      - us
    show_on_map: false
    city: Macarthur
    state: ACT
    country: Australia

####################################################
#                                                  #
#                Season                            #
#                                                  #
####################################################

  - platform: season

####################################################
#                                                  #
#                BOM FTP Sensor                    #
#                                                  #
####################################################

  # - platform: bom_forecast
  #   product_id: IDN60801
  #   name: Isabella Plains
  #   forecast_days: 6
  #   rest_of_today: true
  #   friendly: false
  #   friendly_state_format: '{max}, {summary}'
  #   monitored_conditions:
  #     - 'max'
  #     - 'min'
  #     - 'chance_of_rain'
  #     - 'possible_rainfall'
  #     - 'summary'
  #     - 'detailed_summary'
  #     - 'icon'

####################################################
#                                                  #
#                BOM Sensor                        #
#                                                  #
####################################################


  - platform: bom
    station: IDN60903.94925
    name: Tuggeranong (Isabella Plains) AWS
    monitored_conditions:
      - apparent_t
      - delta_t
      - gust_kmh
      - air_temp
      - dewpt
      - press
      - press_qnh
      - press_msl
      - rain_trace
      - rel_hum
      - vis_km
      - wind_dir
      - wind_spd_kmh

####################################################
#                                                  #
#                Sensor - Darksky Sensor           #
#                                                  #
####################################################

  - platform: darksky
    api_key: !secret darksky_token
    forecast:
      - 0
      - 1
    monitored_conditions:
      - summary
      - precip_probability
      - wind_speed
      - cloud_cover
      - icon
      - temperature_low
      - temperature_high
      - daily_summary
      - hourly_summary
      - precip_intensity
      - precip_accumulation
      - precip_type
      - temperature
      - apparent_temperature
      - wind_bearing
      - humidity
      - pressure
      - uv_index 
    scan_interval:
      minutes: 5

#################################################################
#                                                               #
#                      Camera                                   #
#                                                               #
#################################################################

camera:

####################################################
#                                                  #
#                BOM Radar                         #
#                                                  #
####################################################
     
  - platform: bom
    name: bom_canberra_radar
    location: Canberra
    filename: /config/www/images/canberraradar.gif
    #delta: 600


#################################################################
#                                                               #
#                      Automation                               #
#                                                               #
#################################################################

automation:

####################################################
#                                                  #
#                Lightning in area                 #
#                                                  #
####################################################

  - alias: weather_lightning_strikes_on
    trigger:
      platform: geo_location
      source: wwlln
      zone: zone.Watch
      event: enter  # or "leave"
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.weather_storms

  - alias: weather_lightning_strikes_off
    trigger:
      platform: geo_location
      source: wwlln
      zone: zone.Watch
      event: leave
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.weather_storms


  - alias: weather_fires_on
    trigger:
      platform: geo_location
      source: nsw_rural_fire_service_feed
      zone: zone.Watch
      event: enter  # or "leave"
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.weather_fires

  - alias: weather_fires_off
    trigger:
      platform: geo_location
      source: nsw_rural_fire_service_feed
      zone: zone.Watch
      event: leave
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.weather_fires



####################################################
#                                                  #
#               UV                                 #
#                                                  #
####################################################


  - alias: Update OpenUV every 30 minutes while the sun is at least 10 degrees above the horizon
    trigger:
      platform: time_pattern
      minutes: '/30'
    condition:
      condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      above: 10
    action:
      service: openuv.update_uv_index_data      

  - alias: Update OpenUV protection window four times a day
    trigger:
      - platform: time
        at: "06:12:00"
      - platform: time
        at: "10:12:00"
      - platform: time
        at: "15:12:00"
      - platform: time
        at: "19:12:00"
    action:
      service: openuv.update_protection_data    