#################################################################
#                                                               #
#                     Packages/Bed Warming                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

group:
  weather_e:
    name: Weather Entities
    view: no
    entities:
      - sun.sun
      - sensor.season
      - weather.dark_sky
      - camera.bom_canberra_radar

  weather_bom_e:
    name: Weather BOM Entities
    view: no
    entities:
      - sensor.bom_tuggeranong_isabella_plains_aws_air_temp_c
      - sensor.bom_tuggeranong_isabella_plains_aws_delta_temp_c
      - sensor.bom_tuggeranong_isabella_plains_aws_dew_point_c
      - sensor.bom_tuggeranong_isabella_plains_aws_feels_like_c
      - sensor.bom_tuggeranong_isabella_plains_aws_pressure_mb
      - sensor.bom_tuggeranong_isabella_plains_aws_pressure_msl
      - sensor.bom_tuggeranong_isabella_plains_aws_pressure_qnh
      - sensor.bom_tuggeranong_isabella_plains_aws_rain_today
      - sensor.bom_tuggeranong_isabella_plains_aws_relative_humidity
      - sensor.bom_tuggeranong_isabella_plains_aws_visability_km
      - sensor.bom_tuggeranong_isabella_plains_aws_wind_direction
      - sensor.bom_tuggeranong_isabella_plains_aws_wind_gust_kmh
      - sensor.bom_tuggeranong_isabella_plains_aws_wind_speed_kmh
      
  weather_dsky_e:
    name: Weather Dark Sky Entities
    view: no
    entities:
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_cloud_coverage_0d
      - sensor.dark_sky_cloud_coverage_1d
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_daytime_high_temperature_0d
      - sensor.dark_sky_daytime_high_temperature_1d
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_humidity
      - sensor.dark_sky_humidity_0d
      - sensor.dark_sky_humidity_1d
      - sensor.dark_sky_icon
      - sensor.dark_sky_icon_0d
      - sensor.dark_sky_icon_1d
      - sensor.dark_sky_overnight_low_temperature_0d
      - sensor.dark_sky_overnight_low_temperature_1d
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_0d
      - sensor.dark_sky_precip_1d
      - sensor.dark_sky_precip_accumulation_0d
      - sensor.dark_sky_precip_accumulation_1d
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_intensity_0d
      - sensor.dark_sky_precip_intensity_1d
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_probability_0d
      - sensor.dark_sky_precip_probability_1d
      - sensor.dark_sky_pressure
      - sensor.dark_sky_pressure_0d
      - sensor.dark_sky_pressure_1d
      - sensor.dark_sky_summary
      - sensor.dark_sky_summary_0d
      - sensor.dark_sky_summary_1d
      - sensor.dark_sky_temperature
      - sensor.dark_sky_uv_index
      - sensor.dark_sky_uv_index_0d
      - sensor.dark_sky_uv_index_1d
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_bearing_0d
      - sensor.dark_sky_wind_bearing_1d
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_speed_0d
      - sensor.dark_sky_wind_speed_1d

#################################################################
#                                                               #
#                      Sun                                      #
#                                                               #
#################################################################

sun:

#################################################################
#                                                               #
#                      Weather                                  #
#                                                               #
#################################################################

weather:
  - platform: darksky
    api_key: !secret darksky_token

#################################################################
#                                                               #
#                      Sensors                                  #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                Season                            #
#                                                  #
####################################################

  - platform: season

####################################################
#                                                  #
#                BOM Sensor                        #
#                                                  #
####################################################


  - platform: bom
    station: IDN60903.94925
    name: Tuggeranong (Isabella Plains) AWS
    monitored_conditions:
      - apparent_t
      - delta_t
      - gust_kmh
      - air_temp
      - dewpt
      - press
      - press_qnh
      - press_msl
      - rain_trace
      - rel_hum
      - vis_km
      - wind_dir
      - wind_spd_kmh

####################################################
#                                                  #
#                Sensor - Darksky Sensor           #
#                                                  #
####################################################

  - platform: darksky
    api_key: !secret darksky_token
    forecast:
      - 0
      - 1
    monitored_conditions:
      - summary
      - precip_probability
      - wind_speed
      - cloud_cover
      - icon
      - temperature_low
      - temperature_high
      - daily_summary
      - hourly_summary
      - precip_intensity
      - precip_accumulation
      - precip_type
      - temperature
      - apparent_temperature
      - wind_bearing
      - humidity
      - pressure
      - uv_index 
    scan_interval:
      minutes: 5

#################################################################
#                                                               #
#                      Camera                                   #
#                                                               #
#################################################################

camera:

####################################################
#                                                  #
#                BOM Radar                         #
#                                                  #
####################################################
     
  - platform: bom
    name: bom_canberra_radar
    location: Canberra
    filename: /config/www/images/canberraradar.gif
    #delta: 600
