#################################################################
#                                                               #
#                     Packages/Bed Warming                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

group:
  weather_e:
    name: Weather Entities
    entities:
      - sun.sun
      - sensor.season
      - weather.dark_sky
      - camera.bom_canberra_radar
      - sensor.inside_now
      - input_boolean.weather_storms
      
  weather_dsky_e:
    name: Weather Dark Sky Entities
    entities:
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_cloud_coverage_0d
      - sensor.dark_sky_cloud_coverage_1d
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_daytime_high_temperature_0d
      - sensor.dark_sky_daytime_high_temperature_1d
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_humidity
      - sensor.dark_sky_humidity_0d
      - sensor.dark_sky_humidity_1d
      - sensor.dark_sky_icon
      - sensor.dark_sky_icon_0d
      - sensor.dark_sky_icon_1d
      - sensor.dark_sky_overnight_low_temperature_0d
      - sensor.dark_sky_overnight_low_temperature_1d
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_0d
      - sensor.dark_sky_precip_1d
      - sensor.dark_sky_precip_accumulation_0d
      - sensor.dark_sky_precip_accumulation_1d
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_intensity_0d
      - sensor.dark_sky_precip_intensity_1d
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_probability_0d
      - sensor.dark_sky_precip_probability_1d
      - sensor.dark_sky_pressure
      - sensor.dark_sky_pressure_0d
      - sensor.dark_sky_pressure_1d
      - sensor.dark_sky_summary
      - sensor.dark_sky_summary_0d
      - sensor.dark_sky_summary_1d
      - sensor.dark_sky_temperature
      - sensor.dark_sky_uv_index
      - sensor.dark_sky_uv_index_0d
      - sensor.dark_sky_uv_index_1d
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_bearing_0d
      - sensor.dark_sky_wind_bearing_1d
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_speed_0d
      - sensor.dark_sky_wind_speed_1d

  weather_dam_e:
    name: Weather Dam Entities
    entities:
      - input_boolean.check_dams
      - input_text.dam_act_catchment_total
      - input_text.dam_act_catchment_percent
      - input_text.dam_act_googong_total
      - input_text.dam_act_googong_percent
      - input_text.dam_act_cotter_total
      - input_text.dam_act_cotter_percent
      - input_text.dam_act_corin_total
      - input_text.dam_act_corin_percent
      - input_text.dam_act_bendora_total
      - input_text.dam_act_bendora_percent

#################################################################
#                                                               #
#                      Input Boolean                            #
#                                                               #
#################################################################

input_boolean:

####################################################
#                                                  #
#                weather storms                    #
#                                                  #
####################################################

  weather_storms:
    name: Lightning around home
    icon: mdi:weather-lightning

  weather_fires:
    name: Fires around home
    icon: mdi:fire

#  DAM_FLAG: "input_boolean.check_dams"
  check_dams:
    name: Check ACT Dam levels
    icon: mdi:cup-water

#   ACC_FLAG: "input_boolean.get_allergies_data"
  get_allergies_data:
    name: Get Allergies Data
    icon: mdi:download-network

#   DEB_FLAG: "input_boolean.reset_allergies_sensor"
  reset_allergies_sensor:
    name: Load Allergies Data
    icon: mdi:reload-alert

#################################################################
#                                                               #
#                      Sun                                      #
#                                                               #
#################################################################

sun:

binary_sensor:
  - platform: sun2
    monitored_conditions:
      - elevation

#################################################################
#                                                               #
#                      Weather                                  #
#                                                               #
#################################################################

weather:
  - platform: darksky
    api_key: !secret darksky_token

#################################################################
#                                                               #
#                      NSW Bushfires                            #
#                                                               #
#################################################################

#geo_location:
#  - platform: nsw_rural_fire_service_feed

geo_location:
  - platform: nsw_rural_fire_service_feed
    entity_namespace: 'nsw_fire_service_feed'
    radius: 30
    categories:
      - 'Emergency Warning'
      - 'Watch and Act'
      - 'Advice'

#################################################################
#                                                               #
#                      Sensors                                  #
#                                                               #
#################################################################

sensor:

#################################################################
#                                                               #
#                      Moon    - moved to ui                                #
#                                                               #
#################################################################

#  - platform: moon

#################################################################
#                                                               #
#                      Sun                                     #
#                                                               #
#################################################################

  - platform: sun2
    monitored_conditions:
      - solar_midnight
      - astronomical_dawn
      - nautical_dawn
      - dawn
      - sunrise
      - solar_noon
      - sunset
      - dusk
      - nautical_dusk
      - astronomical_dusk
      - daylight
      - civil_daylight
      - nautical_daylight
      - astronomical_daylight
      - night
      - civil_night
      - nautical_night
      - astronomical_night
      - elevation
      - min_elevation
      - max_elevation

####################################################
#                                                  #
#                Indoor Temp                       #
#                                                  #
####################################################

  - platform: template
    sensors:
      inside_now:
        friendly_name: Temp Inside
        value_template: "{{ states('sensor.back_door_state_temperature_measurement') }}"
        unit_of_measurement: C
      forecast_today_0:
        friendly_name: Today Forecast L1
        value_template: '{{ ( states.sensor.calwell_extended_text_0.state | wordwrap(100, true,"§")).split("§")[0]}}'
      forecast_today_1:
        friendly_name: Today Forecast L2
        value_template: '{{ ( states.sensor.calwell_extended_text_0.state | wordwrap(100, true,"§")).split("§")[1]}}' 
      forecast_today_2:
        friendly_name: Today Forecast L3
        value_template: '{{ ( states.sensor.calwell_extended_text_0.state | wordwrap(100, true,"§")).split("§")[2]}}' 


####################################################
#                                                  #
#                Season  - moved to ui                          #
#                                                  #
####################################################

#  - platform: season


####################################################
#                                                  #
#                Sensor - Darksky Sensor           #
#                                                  #
####################################################

  - platform: darksky
    api_key: !secret darksky_token
    forecast:
      - 0
      - 1
    monitored_conditions:
      - summary
      - precip_probability
      - wind_speed
      - cloud_cover
      - icon
      - temperature_low
      - temperature_high
      - daily_summary
      - hourly_summary
      - precip_intensity
      - precip_accumulation
      - precip_type
      - temperature
      - apparent_temperature
      - wind_bearing
      - humidity
      - pressure
      - uv_index 
    scan_interval:
      minutes: 5




#################################################################
#                                                               #
#                      Automation                               #
#                                                               #
#################################################################

automation:

####################################################
#                                                  #
#                Lightning in area                 #
#                                                  #
####################################################

  - alias: weather_lightning_strikes_on
    trigger:
      platform: geo_location
      source: wwlln
      zone: zone.Watch
      event: enter  # or "leave"
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.weather_storms

  - alias: weather_lightning_strikes_off
    trigger:
      platform: geo_location
      source: wwlln
      zone: zone.Watch
      event: leave
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.weather_storms


  - alias: weather_fires_on
    trigger:
      platform: geo_location
      source: nsw_rural_fire_service_feed
      zone: zone.Watch
      event: enter  # or "leave"
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.weather_fires

  - alias: weather_fires_off
    trigger:
      platform: geo_location
      source: nsw_rural_fire_service_feed
      zone: zone.Watch
      event: leave
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.weather_fires



####################################################
#                                                  #
#               UV                                 #
#                                                  #
####################################################


  