#################################################################
#                                                               #
#                     Packages/Bed Warming                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Input Number                            #
#                                                               #
#################################################################

input_number:

####################################################
#                                                  #
#                Input Numbers - Warm Beds         #
#                                                  #
####################################################

  bed_s_flag:
    min: 5
    max: 15
    name: "Warm Simon's bed"
    #initial: 12
    unit_of_measurement: 'C'
    icon: mdi:hotel

  bed_m_flag:
    min: 5
    max: 15
    name: "Warm Megan's bed"
    #initial: 12
    unit_of_measurement: 'C'
    icon: mdi:hotel

  bed_st_flag:
    min: 5
    max: 15
    name: "Warm Staci's bed"
    #initial: 12
    unit_of_measurement: 'C'
    icon: mdi:hotel

  bed_d_flag:
    min: 5
    max: 15
    name: "Warm Delia's bed"
    #initial: 12
    unit_of_measurement: 'C'
    icon: mdi:hotel
    
#################################################################
#                                                               #
#                            Sensors                            #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                Sensor - Darksky Sensor           #
#                                                  #
####################################################

  - platform: darksky
    api_key: !secret darksky_token
    forecast:
      - 0
      - 1
    monitored_conditions:
      - summary
      - precip_probability
      - wind_speed
      - cloud_cover
      - icon
      - temperature_low
      - temperature_high
      - daily_summary
      - hourly_summary
      - precip_intensity
      - precip_accumulation
      - precip_type
      - temperature
      - apparent_temperature
      - wind_bearing
      - humidity
      - pressure
      - uv_index 
    scan_interval:
      minutes: 5

####################################################
#                                                  #
#                Sensor - Warm Beds                #
#                                                  #
####################################################

  - platform: template
    sensors:
      sbed:
        friendly_name: Warm Simon's bed tonight
        value_template: "{{ states('sensor.dark_sky_overnight_low_temperature_0')|float < states('input_number.bed_s_flag')|float }}"
        icon_template: mdi:radiator
      mbed:
        friendly_name: Warm Megan's bed tonight
        value_template: "{{ states('sensor.dark_sky_overnight_low_temperature_0')|float < states('input_number.bed_m_flag')|float }}"
        icon_template: mdi:radiator
      stbed:
        friendly_name: Warm Staci's bed tonight
        value_template: "{{ states('sensor.dark_sky_overnight_low_temperature_0')|float < states('input_number.bed_st_flag')|float }}"
        icon_template: mdi:radiator
      dbed:
        friendly_name: Warm Delia's bed tonight
        value_template: "{{ states('sensor.dark_sky_overnight_low_temperature_0')|float < states('input_number.bed_d_flag')|float }}"
        icon_template: mdi:radiator
 
#################################################################
#                                                               #
#                            Input Boolean                      #
#                                                               #
#################################################################

input_boolean:

####################################################
#                                                  #
#           Input Boolean - Warm Beds on timer     #
#                                                  #
####################################################

  bed_s:
    name: Simon Bed warm on timer
    initial: off
    icon: mdi:hotel

  bed_m:
    name: Megan Bed warm on timer
    initial: off
    icon: mdi:hotel

  bed_st:
    name: Staci Bed warm on timer
    initial: off
    icon: mdi:hotel

  bed_d:
    name: Delia Bed warm on timer
    initial: off
    icon: mdi:hotel        

#################################################################
#                                                               #
#                            Timers                             #
#                                                               #
#################################################################

timer:

####################################################
#                                                  #
#                Timer  - Warm Beds                #
#                                                  #
####################################################

  bed_s_timer:
    duration: '01:00:00'

  bed_m_timer:
    duration: '01:00:00'

  bed_st_timer:
    duration: '01:00:00'

  bed_d_timer:
    duration: '01:00:00'

#################################################################
#                                                               #
#                            Script                             #
#                                                               #
#################################################################

script:

####################################################
#                                                  #
#                script  - turn on beds prewarm    #
#                                                  #
####################################################

  beds_on_prewarm:
    sequence:
      service: script.turn_on
      entity_id:
        - script.bed_s_on
        - script.bed_m_on
        - script.bed_st_on
        - script.bed_d_on

  bed_s_on:
    sequence:
      - condition: state
        entity_id: binary_sensor.sbed
        state: 'on'
      - service: homeassistant.turn_on
        entity_id: switch.simon_blanket

  bed_m_on:
    sequence:
      - condition: state
        entity_id: binary_sensor.mbed
        state: 'on'
      - service: homeassistant.turn_on
        entity_id: switch.megan_blanket

  bed_st_on:
    sequence:
      - condition: state
        entity_id: binary_sensor.stbed
        state: 'on'
      - service: homeassistant.turn_on
        entity_id: switch.staci_blanket

  bed_d_on:
    sequence:
      - condition: state
        entity_id: binary_sensor.dbed
        state: 'on'
      - service: homeassistant.turn_on
        entity_id: switch.delia_blanket

####################################################
#                                                  #
#                script  - turn on beds timer      #
#                                                  #
####################################################

  beds_on_timer:
    sequence:
      service: script.turn_on
      entity_id:
        - script.bed_s_on_t
        - script.bed_m_on_t
        - script.bed_st_on_t
        - script.bed_d_on_t

  bed_s_on_t:
    sequence:
      - service: homeassistant.turn_on
        entity_id: switch.simon_blanket
      - service: timer.start
        entity_id: timer.bed_s_timer
      

  bed_m_on_t:
    sequence:
      - service: homeassistant.turn_on
        entity_id: switch.megan_blanket
      - service: timer.start
        entity_id: timer.bed_m_timer
      

  bed_st_on_t:
    sequence:
      - service: homeassistant.turn_on
        entity_id: switch.staci_blanket
      - service: timer.start
        entity_id: timer.bed_st_timer
      

  bed_d_on_t:
    sequence:
      - service: homeassistant.turn_on
        entity_id: switch.delia_blanket
      - service: timer.start
        entity_id: timer.bed_d_timer
      

####################################################
#                                                  #
#                script  - turn off beds           #
#                                                  #
####################################################

  beds_off:
    sequence:
      service: script.turn_on
      entity_id:
        - script.bed_s_off
        - script.bed_m_off
        - script.bed_st_off
        - script.bed_d_off

  bed_s_off:
    sequence:
      - service: homeassistant.turn_off
        entity_id: 
          - switch.simon_blanket
          - input_boolean.bed_s

  bed_m_off:
    sequence:
      - service: homeassistant.turn_off
        entity_id: 
          - switch.megan_blanket
          - input_boolean.bed_m

  bed_st_off:
    sequence:
      - service: homeassistant.turn_off
        entity_id: 
          - switch.staci_blanket
          - input_boolean.bed_st

  bed_d_off:
    sequence:
      - service: homeassistant.turn_off
        entity_id: 
          - switch.delia_blanket
          - input_boolean.bed_d

#################################################################
#                                                               #
#                            Automation                         #
#                                                               #
#################################################################

automation:

####################################################
#                                                  #
#                automation - turn on beds         #
# evening mode (if overnight temp cold)
#                                                  #
####################################################

  - alias: bed_auto_on_evening
    trigger:
      - platform: state
        entity_id: binary_sensor.mode_evening
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.beds_on_prewarm

####################################################
#                                                  #
#                automation - turn on beds         #
# flagged on - turn on with timer
#                                                  #
####################################################

  - alias: bed_timer_s
    trigger:
      - platform: state
        entity_id: input_boolean.bed_s
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.bed_s_on_t

  - alias: bed_timer_m
    trigger:
      - platform: state
        entity_id: input_boolean.bed_m
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.bed_m_on_t

  - alias: bed_timer_st
    trigger:
      - platform: state
        entity_id: input_boolean.bed_st
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.bed_st_on_t

  - alias: bed_timer_d
    trigger:
      - platform: state
        entity_id: input_boolean.bed_d
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.bed_d_on_t

####################################################
#                                                  #
#                automation  - turn off beds       #
# timer done, night, day or morning modes
#                                                  #
####################################################

  - alias: bed_s_auto_off
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.bed_s_timer
      - platform: state
        entity_id: binary_sensor.mode_night
        to: 'on'
      - platform: state
        entity_id: binary_sensor.mode_day
        to: 'on'
      - platform: state
        entity_id: binary_sensor.mode_morning
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.bed_s_off

  - alias: bed_m_auto_off
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.bed_m_timer
      - platform: state
        entity_id: binary_sensor.mode_night
        to: 'on'
      - platform: state
        entity_id: binary_sensor.mode_day
        to: 'on'
      - platform: state
        entity_id: binary_sensor.mode_morning
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.bed_m_off

  - alias: bed_st_auto_off
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.bed_st_timer
      - platform: state
        entity_id: binary_sensor.mode_night
        to: 'on'
      - platform: state
        entity_id: binary_sensor.mode_day
        to: 'on'
      - platform: state
        entity_id: binary_sensor.mode_morning
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.bed_st_off

  - alias: bed_d_auto_off
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.bed_d_timer
      - platform: state
        entity_id: binary_sensor.mode_night
        to: 'on'
      - platform: state
        entity_id: binary_sensor.mode_day
        to: 'on'
      - platform: state
        entity_id: binary_sensor.mode_morning
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.bed_d_off