#################################################################
#                                                               #
#                     Packages/Bed Warming                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

group:
  bedwarm_e:
    name: Bed Warm Entities
    entities:
      #- Personal Low Number
      - input_number.bed_s_flag
      - input_number.bed_m_flag
      - input_number.bed_st_flag
      - input_number.bed_d_flag
      #- Flag - Will it turn on tonight?
      - binary_sensor.sbed
      - binary_sensor.mbed
      - binary_sensor.stbed
      - binary_sensor.dbed
      #- Flag - Is it currently on?
      - input_boolean.bed_s
      - input_boolean.bed_m
      - input_boolean.bed_st
      - input_boolean.bed_d
      #- Timer
      - timer.bed_s_timer
      - timer.bed_m_timer
      - timer.bed_st_timer
      - timer.bed_d_timer


#################################################################
#                                                               #
#                       Input Number                            #
#                                                               #
#################################################################

input_number:

####################################################
#                                                  #
#                Input Numbers - Warm Beds         #
#                                                  #
# Personal Low Numbers, what overnight temperature 
# do you want the blanket switched on at?
#                                                 #
####################################################

  bed_s_flag:
    min: 5
    max: 15
    name: "Warm Simon's bed"
    unit_of_measurement: 'C'
    icon: mdi:hotel

  bed_m_flag:
    min: 5
    max: 15
    name: "Warm Megan's bed"
    unit_of_measurement: 'C'
    icon: mdi:hotel

  bed_st_flag:
    min: 5
    max: 15
    name: "Warm Staci's bed"
    unit_of_measurement: 'C'
    icon: mdi:hotel

  bed_d_flag:
    min: 5
    max: 15
    name: "Warm Delia's bed"
    unit_of_measurement: 'C'
    icon: mdi:hotel
    
#################################################################
#                                                               #
#                  Binary Sensors                               #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#        Binary Sensor - Warm Beds                #
#                                                  #
####################################################

  - platform: template
    sensors:
      sbed:
        friendly_name: Warm Simon's bed tonight
        value_template: "{{ is_state('input_boolean.away_simon', 'off') and states('sensor.dark_sky_overnight_low_temperature_0d')|float < states('input_number.bed_s_flag')|float }}"
        icon_template: mdi:radiator
      mbed:
        friendly_name: Warm Megan's bed tonight
        value_template: "{{ is_state('input_boolean.away_megan', 'off') and states('sensor.dark_sky_overnight_low_temperature_0d')|float < states('input_number.bed_m_flag')|float }}"
        icon_template: mdi:radiator
      stbed:
        friendly_name: Warm Staci's bed tonight
        value_template: "{{ is_state('input_boolean.away_staci', 'off') and states('sensor.dark_sky_overnight_low_temperature_0d')|float < states('input_number.bed_st_flag')|float }}"
        icon_template: mdi:radiator
      dbed:
        friendly_name: Warm Delia's bed tonight
        value_template: "{{ is_state('input_boolean.away_delia', 'off') and states('sensor.dark_sky_overnight_low_temperature_0d')|float < states('input_number.bed_d_flag')|float }}"
        icon_template: mdi:radiator

#################################################################
#                                                               #
#                            Input Boolean                      #
#                                                               #
#################################################################

input_boolean:

####################################################
#                                                  #
#           Input Boolean - Warm Beds on timer     #
#                                                  #
####################################################

  bed_s:
    name: Simon Bed warm on timer
    initial: off
    icon: mdi:hotel

  bed_m:
    name: Megan Bed warm on timer
    initial: off
    icon: mdi:hotel

  bed_st:
    name: Staci Bed warm on timer
    initial: off
    icon: mdi:hotel

  bed_d:
    name: Delia Bed warm on timer
    initial: off
    icon: mdi:hotel        

#################################################################
#                                                               #
#                            Timers                             #
#                                                               #
#################################################################

timer:

####################################################
#                                                  #
#                Timer  - Warm Beds                #
#                                                  #
####################################################

  bed_s_timer:
    duration: '01:00:00'

  bed_m_timer:
    duration: '01:00:00'

  bed_st_timer:
    duration: '01:00:00'

  bed_d_timer:
    duration: '01:00:00'

#################################################################
#                                                               #
#                            Automation                         #
#                                                               #
#################################################################

# See Node-Red
# Climate
# Time Actions
# Remotes and Buttons
# Timers

