#################################################################
#                                                               #
#                     Packages/Pi-Hole                          #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

group:
  pi_hole_e:
    name: Pi-Hole Entities
    view: no
    entities:
      - sensor.pi_hole_ads_blocked_today
      - sensor.pi_hole_domains_being_blocked
      - sensor.pi_hole_dns_queries_today
      - sensor.pi_hole_unique_clients
      
#################################################################
#                                                               #
#                            Sensors                            #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                Sensor - Pi-hole                  #
#                                                  #
####################################################

#  - platform: pi_hole
#    host: 192.168.1.46:4865
#    ssl: true
#    verify_ssl: false
#    monitored_conditions:
#      - ads_blocked_today
#      - domains_being_blocked
#      - dns_queries_today
#      - unique_clients
      
