#################################################################
#                                                               #
#                     Packages/Garage Door                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

group:
  garage_door_e:
    name: Garage Door Entities
    view: no
    entities:
      - cover.near_garage_door
      - binary_sensor.roller_close
      - binary_sensor.roller_open

  # garage_door_a:
  #   name: Garage Door Automations
  #   view: no
  #   entities:
  #     - automation.
  #     - automation.
  #     - automation.
  #     - automation.

#################################################################
#                                                               #
#                Cover - MyQ Connection                         #
#                                                               #
#################################################################

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: chamberlain


#################################################################
#                                                               #
#               Binary Sensor                                   #
#                                                               #
#################################################################

binary_sensor:

  - platform: template
    sensors:
      roller_close:
        friendly_name: Garage Close
        value_template: "{{ is_state('cover.near_garage_door', 'closed') }}"
        icon_template: mdi:garage
        device_class: motion
      roller_open:
        friendly_name: Garage Open
        value_template: "{{ is_state('binary_sensor.roller_close', 'off') }}"
        icon_template: mdi:garage-open
        device_class: opening

#################################################################
#                                                               #
#                       Automation                              #
#                                                               #
#################################################################

# please see appdaemon

  