#################################################################
#                                                               #
#                     Packages/Batteries                        #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

group:
  batteries_e:
    name: Batteries Entities
    entities:
      #- Integrations
      #- Phone batteries - via app
      - sensor.megans_ipad_battery_level
      - sensor.megans_ipad_battery_state
      - sensor.moto_g_5s_plus_battery_level
      - sensor.pixel_3_battery_level
      - sensor.pixel_3a_battery_level
      - sensor.sm_g965f_battery_level
      #- smoke detectors
      - sensor.back_hall_nest_protect_battery_health
      - sensor.hallway_nest_protect_battery_health
      #- smartthings multisensors
      - sensor.back_door_state_battery
      - sensor.front_door_state_battery
      - sensor.dishwasher_multipurpose_sensor_battery            
      #- smartthings motion sensors
      - sensor.bathroom_motion_battery
      - sensor.toilet_motion_battery      
      #- smartthings water leak sensors
      - sensor.bathroom_water_leak_sensor_battery
      - sensor.dishwasher_water_leak_sensor_battery
      - sensor.ensuite_water_leak_sensor_battery
      - sensor.kitchen_water_leak_sensor_battery
      - sensor.laundry_water_leak_sensor_battery
      #- smartthings buttons
      - sensor.megs_button_battery
      #- Hue - coded - see below
      - sensor.ensuite_motion_sensor_battery_level
      - sensor.laundry_motion_sensor_battery_level
      - sensor.garage_motion_sensor_battery_level
      - sensor.living_room_hue_remote_battery_level
      - sensor.bedroom_hue_remote_battery_level
      - sensor.bedroom_2_hue_remote_battery_level
      #---------------- binaries
      - binary_sensor.simon_batt_low
      - binary_sensor.megan_batt_low
      - binary_sensor.staci_batt_low
      - binary_sensor.delia_batt_low
      - binary_sensor.megan_ipad_batt_low
      #---------------- phone battery notification
      - input_number.batt_alert
      - input_boolean.batt_notify_system
      #---------------- device battery notification
      - input_number.dbatt_alert
      - input_boolean.dbatt_notify_system

  # batteries_a:
  #   name: Batteries Automations
  #   entities:
  #     - automation.
  #     - automation.
  #     - automation.
  #     - automation.

#################################################################
#                                                               #
#                       Binary Sensors                          #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#            Binary Sensors - Phone Batteries      #
#                                                  #
#################################################### 

  - platform: template
    sensors:
      simon_batt_low:
        friendly_name: Simon Battery Low
        value_template: "{{ states('sensor.pixel_3_battery_level')|float < states('input_number.batt_alert')|float }}"
        icon_template: mdi:battery-10
      megan_batt_low:
        friendly_name: Megan Battery Low
        value_template: "{{ states('sensor.sm_g965f_battery_level')|float < states('input_number.batt_alert')|float }}"
        icon_template: mdi:battery-10
      staci_batt_low:
        friendly_name: Staci Battery Low
        value_template: "{{ states('sensor.pixel_3a_battery_level')|float < states('input_number.batt_alert')|float }}"
        icon_template: mdi:battery-10
      delia_batt_low: 
        friendly_name: Delia Battery Low
        value_template: "{{ states('sensor.moto_g_5s_plus_battery_level')|float < states('input_number.batt_alert')|float }}"
        icon_template: mdi:battery-10
      megan_ipad_batt_low:
        friendly_name: Megan iPad Battery Low
        value_template: "{{ states('sensor.megans_ipad_battery_level')|float < states('input_number.batt_alert')|float }}"
        icon_template: mdi:battery-10


#################################################################
#                                                               #
#                       Input Boolean                           #
#                                                               #
#################################################################

input_boolean:

####################################################
#                                                  #
#            Input Boolean - battery Notify system     #
#                                                  #
#################################################### 

  batt_notify_system:
    name: Battery Message
    initial: off
    icon: mdi:battery-10

  dbatt_notify_system:
    name: Device Battery Message
    initial: off
    icon: mdi:battery-10

#################################################################
#                                                               #
#                       Input Number                            #
#                                                               #
#################################################################

input_number:

####################################################
#                                                  #
#                Input Numbers - ink message       #
#                                                  #
####################################################

  batt_alert:
    min: 0
    max: 100
    name: 'Phone Battery Notify at'
    unit_of_measurement: '%'
    icon: mdi:alarm-bell

  dbatt_alert:
    min: 10
    max: 50
    name: 'Device Battery Notify at'
    unit_of_measurement: '%'
    icon: mdi:alarm-bell

#################################################################
#                                                               #
#                       Sensor                                  #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#           sensor - hue motion sensors            #
#                                                  #
####################################################      

  - platform: rest
    resource: !secret hue_ens_temp
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Ensuite Motion Sensor Battery Level'

  - platform: rest
    resource: !secret hue_lnd_temp
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Laundry Motion Sensor Battery Level'

  - platform: rest
    resource: !secret hue_gar_temp
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Garage Motion Sensor Battery Level'

####################################################
#                                                  #
#           sensor - hue remotes                   #
#                                                  #
#################################################### 

  - platform: rest
    resource: !secret hue_rem_liv
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Living Room Hue Remote Battery Level'

  - platform: rest
    resource: !secret hue_rem_bed
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Bedroom Hue Remote Battery Level'

  - platform: rest
    resource: !secret hue_rem_mbed
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Bedroom 2 Hue Remote Battery Level'

#################################################################
#                                                               #
#                       Automation                              #
#                                                               #
#################################################################

# please see appdaemon
