#################################################################
#                                                               #
#                     Packages/System Monitor                   #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

group:
  hub_e:
    name: Hub Network Entities
    view: no
    entities:
      - device_tracker.fan_hub
      - device_tracker.harmonyhub
      - device_tracker.philips_hue
      - device_tracker.kevo_hub
      - device_tracker.myq_hub
      - device_tracker.smartthings_wifi
      #- device_tracker.tradfri_hub

  hub_s:
    name: Hub System
    view: no
    entities:
      - binary_sensor.hubs_system
      - binary_sensor.bond
      - binary_sensor.harmony
      - binary_sensor.hue
      - binary_sensor.kevo
      - binary_sensor.myq
      - binary_sensor.smart
      - binary_sensor.epson
      - binary_sensor.hass_lt
      #- binary_sensor.tradfri

  network_e:
    name: Network Entities
    view: no
    entities:
      - device_tracker.orbi_kitchen
      - device_tracker.orbi_lounge
      - device_tracker.xubuntu_laptop
      - device_tracker.epson_printer
      
  network_s:
    name: Network System
    view: no
    entities:
      - binary_sensor.net_system
      - binary_sensor.wifi_kitchen
      - binary_sensor.wifi_lounge
      - binary_sensor.pi_hole

  media_e:
    name: Media Entities
    view: no
    entities:
      - device_tracker.kitchen_home_speaker
      - device_tracker.ensuite_mini_speaker
      - device_tracker.lounge_mini_speaker
      - device_tracker.lounge_chromecast
      - device_tracker.gaming_chromecast
      - device_tracker.sharp_tv
      - device_tracker.ps4
      
  media_s:
    name: Media System
    view: no
    entities:
      - binary_sensor.media_system
      - binary_sensor.sp_kitchen
      - binary_sensor.sp_lounge
      - binary_sensor.sp_ensuite
      - binary_sensor.sp_ltv
      - binary_sensor.sp_gtv
      - binary_sensor.fetchtv
      - binary_sensor.sonyps4

  app_e:
    name: Appliance Entities
    view: no
    entities:
      - device_tracker.samsung_washer
      - device_tracker.samsung_dryer
      #smartthings
      - switch.washer_samsung
      - sensor.washer_samsung_washer_job_state
      - sensor.washer_samsung_washer_machine_state
      - sensor.washer_samsung_washer_completion_time
      - sensor.washer_samsung_washer_mode
      - switch.tumble_dryer
      - sensor.tumble_dryer_dryer_mode
      - sensor.tumble_dryer_dryer_job_state
      - sensor.tumble_dryer_dryer_machine_state
      - sensor.tumble_dryer_dryer_completion_time

  app_s:
    name: Appliance System
    view: no
    entities:
      - binary_sensor.app_system
      - binary_sensor.samwash
      - binary_sensor.samdry
         
  water_e:
    name: Leak Sensors
    view: no
    entities:
      - binary_sensor.water_leak_yes
      - binary_sensor.water_leak_no
      - binary_sensor.kitchen_water_leak_sensor_water
      - binary_sensor.dishwasher_water_leak_sensor_water
      - binary_sensor.laundry_water_leak_sensor_water
      - binary_sensor.bathroom_water_leak_sensor_water
      - binary_sensor.ensuite_water_leak_sensor_water

  hometab_e:
    name: HomeTab Entities
    view: no
    entities:
      - device_tracker.hometab_study
      - device_tracker.hometab_kitchen
      - device_tracker.hometab_hall
      
  hometab_s:
    name: HomeTab System
    view: no
    entities:
      - binary_sensor.ht_system
      - binary_sensor.ht_study
      - binary_sensor.ht_kitchen
      - binary_sensor.ht_hall
      
  pdevices_e:
    name: Personal Devices Entities
    view: no
    entities:
      - device_tracker.simon_watch
      - device_tracker.simon_tablet
      - device_tracker.simon_desktop
      - device_tracker.simon_surface
      - device_tracker.meg_desktop
      - device_tracker.meg_ipad
      - device_tracker.meg_fitbit
      - device_tracker.meg_work_surface
      - device_tracker.meg_surface
      - device_tracker.staci_surface
      - device_tracker.delia_surface
      - device_tracker.delia_chromebook
      
#################################################################
#                                                               #
#                  Device Trackers                              #
#                                                               #
#################################################################

# track devices 
device_tracker:
  #- platform: nmap_tracker
  #  hosts: 
  #    - 192.168.1.0/24
  #  interval_seconds: 15
  #  consider_home: 180
  #  exclude:
  #   - !secret hass_wired
  #  new_device_defaults:
  #    track_new_devices: yes
  #    hide_if_away: False
  - platform: netgear
    host: 10.0.0.1
    port: 80
    accesspoints: 
      - 78:D2:94:AA:52:44
      - 78:D2:94:AA:76:0C
    username: !secret netgear_user
    password: !secret netgear_pass
    interval_seconds: 10
    consider_home: 180
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false

  - platform: tile
    username: !secret tile_user
    password: !secret tile_pass

#other device tracking - to be turned on when ready
  #- platform: gpslogger
  #- platform: trackr
  #  username: !secret trackr_username
  #  password: !secret trackr_password

#################################################################
#                                                               #
#                   Binary Sensors                              #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#                Binary Sensor - water leaks       #
#                                                  #
####################################################

  - platform: template
    sensors:
      water_leak_yes:
        value_template: "{{ is_state('binary_sensor.kitchen_water_leak_sensor_water', 'on') or is_state('binary_sensor.dishwasher_water_leak_sensor_water', 'on') or is_state('binary_sensor.laundry_water_leak_sensor_water', 'on') or is_state('binary_sensor.bathroom_water_leak_sensor_water', 'on') or is_state('binary_sensor.ensuite_water_leak_sensor_water', 'on') }}"
        friendly_name: 'Water Leak!'
        device_class: moisture
        icon_template: mdi:water
      water_leak_no:
        value_template: "{{ is_state('binary_sensor.water_leak_yes', 'off') }}"
        friendly_name: 'House Dry'
        device_class: connectivity
        icon_template: mdi:water-off

####################################################
#                                                  #
#                Binary Sensor - hubs              #
#                                                  #
####################################################

  - platform: template
    sensors:
      hubs_system:
        #value_template: "{{ is_state('binary_sensor.bond', 'on') and is_state('binary_sensor.harmony', 'on') and is_state('binary_sensor.hue', 'on') and is_state('binary_sensor.kevo', 'on') and is_state('binary_sensor.myq', 'on') and is_state('binary_sensor.smart', 'on') and is_state('binary_sensor.epson', 'on') and is_state('binary_sensor.tradfri', 'on') }}"
        value_template: "{{ is_state('binary_sensor.bond', 'on') and is_state('binary_sensor.harmony', 'on') and is_state('binary_sensor.hue', 'on') and is_state('binary_sensor.kevo', 'on') and is_state('binary_sensor.myq', 'on') and is_state('binary_sensor.smart', 'on') and is_state('binary_sensor.epson', 'on') }}"
        friendly_name: 'Hubs'
        device_class: connectivity
        icon_template: mdi:battlenet
      bond:
        value_template: "{{ is_state('device_tracker.fan_hub', 'home') }}"
        friendly_name: 'Fan Hub'
        device_class: connectivity
        icon_template: mdi:fan
      harmony:
        value_template: "{{ is_state('device_tracker.harmonyhub', 'home') }}"
        friendly_name: 'Remote Hub'
        device_class: connectivity
        icon_template: mdi:remote
      hue:
        value_template: "{{ is_state('device_tracker.philips_hue', 'home') }}"
        friendly_name: 'Lights Hub'
        device_class: connectivity
        icon_template: mdi:ceiling-light
      kevo:
        value_template: "{{ is_state('device_tracker.kevo_hub', 'home') }}"
        friendly_name: 'Locks Hub'
        device_class: connectivity
        icon_template: mdi:home-lock
      myq:
        value_template: "{{ is_state('device_tracker.myq_hub', 'home') }}"
        friendly_name: 'Garage Door Hub'
        device_class: connectivity
        icon_template: mdi:garage
      smart:
        value_template: "{{ is_state('device_tracker.smartthings_wifi', 'home') }}"
        friendly_name: 'Smartthings Hub'
        device_class: connectivity
        icon_template: mdi:home-circle
      epson:
        value_template: "{{ is_state('device_tracker.epson_printer', 'home') }}"
        friendly_name: 'Printer'
        device_class: connectivity
        icon_template: mdi:printer
      ha_laptop:
        value_template: "{{ is_state('device_tracker.ha_laptop', 'home') }}"
        friendly_name: 'Hassio Server'
        device_class: connectivity
        icon_template: mdi:home-assistant
      # hass_lt:
      #   value_template: "{{ is_state('device_tracker.xubuntu_laptop', 'home') }}"
      #   friendly_name: 'Hassio Server'
      #   device_class: connectivity
      #   icon_template: mdi:home-assistant
      # tradfri:
      #   value_template: "{{ is_state('device_tracker.tradfri_hub', 'home') }}"
      #   friendly_name: 'Tradfri Hub'
      #   device_class: connectivity
      #   icon_template: mdi:format-strikethrough

####################################################
#                                                  #
#                Binary Sensor - network           #
#                                                  #
####################################################


  - platform: template
    sensors:
      net_system:
        value_template: "{{ is_state('binary_sensor.wifi_lounge', 'on') and is_state('binary_sensor.wifi_kitchen', 'on')  }}"
        friendly_name: 'Wifi'
        device_class: connectivity
        icon_template: mdi:orbit
      wifi_lounge:
        value_template: "{{ is_state('device_tracker.orbi_lounge', 'home') }}"
        friendly_name: 'Wifi Lounge/Satelite'
        device_class: connectivity
        icon_template: mdi:orbit
      wifi_kitchen:
        value_template: "{{ is_state('device_tracker.orbi_kitchen', 'home') }}"
        friendly_name: 'Wifi Kitchen/Router'
        device_class: connectivity
        icon_template: mdi:orbit
      

      hass_lt_w:
        value_template: "{{ is_state('device_tracker.xubuntu_laptop_w', 'home') }}"
        friendly_name: 'Hassio Server via Wifi'
        device_class: connectivity
        icon_template: mdi:home-assistant
      pi_server:
        value_template: "{{ is_state('device_tracker.pi_server', 'home') }}"
        friendly_name: 'Pi Server'
        device_class: connectivity
        icon_template: mdi:raspberry-pi
      # pi_hole:
      #   value_template: "{{ states('sensor.pi_hole_dns_unique_clients')|float > 0 }}"
      #   friendly_name: 'Pi Hole'
      #   device_class: connectivity
      #   icon_template: mdi:fire

####################################################
#                                                  #
#                Binary Sensor - media             #
#                                                  #
####################################################

  - platform: template
    sensors:
      media_system:
        value_template: "{{ is_state('binary_sensor.sp_kitchen', 'on') and is_state('binary_sensor.sp_lounge', 'on') and is_state('binary_sensor.sp_bathroom', 'on') and is_state('binary_sensor.sp_ltv', 'on') and is_state('binary_sensor.sp_gtv', 'on') and is_state('binary_sensor.sharptv', 'on') and is_state('binary_sensor.sonyps4', 'on') }}"
        friendly_name: 'Speaker/Chromecasts'
        device_class: connectivity
        icon_template: mdi:speaker
      sp_kitchen:
        value_template: "{{ is_state('device_tracker.kitchen_home_speaker', 'home') }}"
        friendly_name: 'Kitchen Home'
        device_class: connectivity
        icon_template: mdi:google-home 
      sp_lounge:
        value_template: "{{ is_state('device_tracker.lounge_mini_speaker', 'home') }}"
        friendly_name: 'Lounge Mini'
        device_class: connectivity
        icon_template: mdi:google-home
      sp_ensuite:
        value_template: "{{ is_state('device_tracker.home_mini_bathroom', 'home') }}"
        friendly_name: 'Ensuite Mini'
        device_class: connectivity
        icon_template: mdi:google-home
      sp_ltv:
        value_template: "{{ is_state('device_tracker.lounge_chromecast', 'home') }}"
        friendly_name: 'Lounge TV'
        device_class: connectivity
        icon_template: mdi:google-chrome
      sp_gtv:
        value_template: "{{ is_state('device_tracker.gaming_chromecast', 'home') }}"
        friendly_name: 'Gaming TV'
        device_class: connectivity
        icon_template: mdi:google-chrome
      sharptv:
        value_template: "{{ is_state('device_tracker.sharp_tv', 'home') }}"
        friendly_name: 'Sharp TV'
        device_class: connectivity
        icon_template: mdi:television-box
      sonyps4:
        value_template: "{{ is_state('device_tracker.ps4', 'home') }}"
        friendly_name: 'PS4 Console'
        device_class: connectivity
        icon_template: mdi:playstation

####################################################
#                                                  #
#                Binary Sensor - Appliance         #
#                                                  #
####################################################

  - platform: template
    sensors:
      app_system:
        value_template: "{{ is_state('binary_sensor.samwash', 'on') and is_state('binary_sensor.samdry', 'on') }}"
        friendly_name: 'Appliances'
        device_class: connectivity
        icon_template: mdi:dishwasher
      samwash:
        value_template: "{{ is_state('device_tracker.samsung_washer', 'home') }}"
        friendly_name: 'Washing Machine'
        device_class: connectivity
        icon_template: mdi:washing-machine
      samdry:
        value_template: "{{ is_state('device_tracker.samsung_dryer', 'home') }}"
        friendly_name: 'Clothes Dryer'
        device_class: connectivity
        icon_template: mdi:tumble-dryer
      # samwash_sw:
      #   value_template: "{{ is_state('switch.washing_machine', 'on') }}"
      #   friendly_name: 'Washing Machine'
      #   device_class: connectivity
      #   icon_template: mdi:washing-machine
      # samdry_sw:
      #   value_template: "{{ is_state('switch.tumble_dryer', 'on') }}"
      #   friendly_name: 'Clothes Dryer'
      #   device_class: connectivity
      #   icon_template: mdi:tumble-dryer

####################################################
#                                                  #
#                Binary Sensor - HomeTabs          #
#                                                  #
####################################################


  - platform: template
    sensors:
      ht_study:
        value_template: "{{ is_state('device_tracker.hometab_study', 'home') }}"
        friendly_name: 'Study'
        device_class: connectivity
        icon_template: mdi:desktop-classic
      ht_kitchen:
        value_template: "{{ is_state('device_tracker.hometab_kitchen', 'home') }}"
        friendly_name: 'Kitchen'
        device_class: connectivity
        icon_template: mdi:fridge-outline
      ht_hall:
        value_template: "{{ is_state('device_tracker.hometab_hall', 'home') }}"
        friendly_name: 'Back Hall'
        device_class: connectivity
        icon_template: mdi:door-closed
      ht_system:
        value_template: "{{ is_state('binary_sensor.ht_hall', 'on') and is_state('binary_sensor.ht_kitchen', 'on') and is_state('binary_sensor.ht_study', 'on') }}"
        friendly_name: 'HomeTabs'
        device_class: connectivity
        icon_template: mdi:tab


      
####################################################
#                                                  #
#               button automation          #
#                   
#   three states - pushed, double, held                            
####################################################

#Megs Button
# automation:

#   - alias: a_mbutton_pushed
#     trigger:
#       platform: event
#       event_type: "smartthings.button"
#       event_data:
#         device_id: "a16b7974-2253-4130-88ec-34a4d5a95796"
#         value: "pushed"
#     action:
#       - service: homeassistant.turn_on
#         entity_id: input_boolean.button_pushed

#   - alias: a_mbutton_held
#     trigger:
#       platform: event
#       event_type: "smartthings.button"
#       event_data:
#         device_id: "a16b7974-2253-4130-88ec-34a4d5a95796"
#         #name: "Megs_button"
#         value: "held"
#     action:
#       - service: homeassistant.turn_off
#         entity_id: input_boolean.button_pushed
