#################################################################
#                                                               #
#                     Packages/System Monitor                   #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

     
#################################################################
#                                                               #
#                  Device Trackers                              #
#                                                               #
#################################################################

# device_tracker:
#   - platform: nmap_tracker
#     hosts: 10.7.7.1/24
#     home_interval: 3
#     interval_seconds: 30

#################################################################
#                                                               #
#                  Vacuum                           #
#                                                               #
#################################################################

# ecovacs:
#   username: !secret eco_user
#   password: !secret eco_pass
#   country: !secret eco_country
#   continent: !secret eco_continent


#################################################################
#                                                               #
#                   Binary Sensors                              #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#                Binary Sensor - water leaks       #
#                                                  #
####################################################

  - platform: template
    sensors:
      water_leak_yes:
        value_template: "{{ is_state('binary_sensor.kitchen_water_leak_sensor_water', 'on') or is_state('binary_sensor.dishwasher_water_leak_sensor_water', 'on') or is_state('binary_sensor.laundry_water_leak_sensor_water', 'on') or is_state('binary_sensor.bathroom_water_leak_sensor_water', 'on') or is_state('binary_sensor.ensuite_water_leak_sensor_water', 'on') or is_state('binary_sensor.lumi_lumi_sensor_wleak_aq1_iaszone_2', 'on') or is_state('binary_sensor.lumi_lumi_sensor_wleak_aq1_iaszone', 'on')}}"
        friendly_name: 'Water Leak!'
        device_class: moisture
        icon_template: mdi:water
      water_leak_no:
        value_template: "{{ is_state('binary_sensor.water_leak_yes', 'off') }}"
        friendly_name: 'House Dry'
        device_class: connectivity
        icon_template: mdi:water-off

####################################################
#                                                  #
#                Binary Sensor - hubs              #
#                                                  #
####################################################

  - platform: template
    sensors:
      hubs_system:
        value_template: "{{ is_state('binary_sensor.harmony', 'on') and is_state('binary_sensor.hue', 'on') and is_state('binary_sensor.myq', 'on') and is_state('binary_sensor.smart', 'on') and is_state('binary_sensor.hub_2_far_myq_gateway', 'on') }}"
        friendly_name: 'Hubs'
        device_class: connectivity
        icon_template: mdi:battlenet
      harmony:
        value_template: "{{ is_state('device_tracker.harmonyhub', 'home') }}"
        friendly_name: 'Remote Hub'
        device_class: connectivity
        icon_template: mdi:remote
      hue:
        value_template: "{{ is_state('device_tracker.philips_hue', 'home') }}"
        friendly_name: 'Lights Hub'
        device_class: connectivity
        icon_template: mdi:ceiling-light
      myq:
        value_template: "{{ is_state('binary_sensor.myq_myq_gateway', 'home') }}"
        friendly_name: 'Garage Door Near'
        device_class: connectivity
        icon_template: mdi:garage
      myq2:
        value_template: "{{ is_state('binary_sensor.hub_2_far_myq_gateway', 'home') }}"
        friendly_name: 'Garage Door Far'
        device_class: connectivity
        icon_template: mdi:garage
      smart:
        value_template: "{{ is_state('device_tracker.smartthings_wifi', 'home') }}"
        friendly_name: 'Smartthings Hub'
        device_class: connectivity
        icon_template: mdi:home-circle
      epson:
        value_template: "{{ is_state('device_tracker.epson_printer', 'home') }}"
        friendly_name: 'Epson Printer'
        device_class: connectivity
        icon_template: mdi:printer
      laser:
        value_template: "{{ is_state('device_tracker.printer_laser_kyocera', 'home') }}"
        friendly_name: 'Kyocera Printer'
        device_class: connectivity
        icon_template: mdi:printer
      

      # tradfri:
      #   value_template: "{{ is_state('device_tracker.tradfri_hub', 'home') }}"
      #   friendly_name: 'Tradfri Hub'
      #   device_class: connectivity
      #   icon_template: mdi:format-strikethrough

####################################################
#                                                  #
#                Binary Sensor - network           #
#                                                  #
####################################################


  # - platform: template
  #   sensors:
  #     net_system:
  #       value_template: "{{ is_state('binary_sensor.wifi_lounge', 'on') and is_state('binary_sensor.wifi_kitchen', 'on')  }}"
  #       friendly_name: 'Wifi'
  #       device_class: connectivity
  #       icon_template: mdi:orbit
  #     wifi_lounge:
  #       value_template: "{{ is_state('device_tracker.orbi_lounge', 'home') }}"
  #       friendly_name: 'Wifi Lounge/Satelite'
  #       device_class: connectivity
  #       icon_template: mdi:orbit
  #     wifi_kitchen:
  #       value_template: "{{ is_state('device_tracker.orbi_kitchen', 'home') }}"
  #       friendly_name: 'Wifi Kitchen/Router'
  #       device_class: connectivity
  #       icon_template: mdi:orbit
      
  #     pi_server:
  #       value_template: "{{ is_state('device_tracker.raspberrypi', 'home') }}"
  #       friendly_name: 'Pi Server'
  #       device_class: connectivity
  #       icon_template: mdi:raspberry-pi
     


####################################################
#                                                  #
#                Binary Sensor - media             #
#                                                  #
####################################################

  # - platform: template
  #   sensors:
  #     media_system:
  #       value_template: "{{ is_state('binary_sensor.sp_kitchen', 'on') and is_state('binary_sensor.sp_lounge', 'on') and is_state('binary_sensor.sp_bathroom', 'on') and is_state('binary_sensor.sp_ltv', 'on') and is_state('binary_sensor.sp_gtv', 'on') and is_state('binary_sensor.sharptv', 'on') and is_state('binary_sensor.sonyps4', 'on') }}"
  #       friendly_name: 'Speaker/Chromecasts'
  #       device_class: connectivity
  #       icon_template: mdi:speaker
  #     sp_kitchen:
  #       value_template: "{{ is_state('device_tracker.kitchen_home_speaker', 'home') }}"
  #       friendly_name: 'Kitchen Home'
  #       device_class: connectivity
  #       icon_template: mdi:google-home 
  #     sp_lounge:
  #       value_template: "{{ is_state('device_tracker.lounge_mini_speaker', 'home') }}"
  #       friendly_name: 'Lounge Mini'
  #       device_class: connectivity
  #       icon_template: mdi:google-home
  #     sp_ensuite:
  #       value_template: "{{ is_state('device_tracker.home_mini_bathroom', 'home') }}"
  #       friendly_name: 'Ensuite Mini'
  #       device_class: connectivity
  #       icon_template: mdi:google-home
  #     sp_ltv:
  #       value_template: "{{ is_state('device_tracker.lounge_chromecast', 'home') }}"
  #       friendly_name: 'Lounge TV'
  #       device_class: connectivity
  #       icon_template: mdi:google-chrome
  #     sp_gtv:
  #       value_template: "{{ is_state('device_tracker.gaming_chromecast', 'home') }}"
  #       friendly_name: 'Gaming TV'
  #       device_class: connectivity
  #       icon_template: mdi:google-chrome
  #     sp_delia:
  #       value_template: "{{ is_state('device_tracker.delia_nest_mini', 'home') }}"
  #       friendly_name: 'Delia Mini'
  #       device_class: connectivity
  #       icon_template: mdi:google-chrome
  #     sharptv:
  #       value_template: "{{ is_state('device_tracker.sharp_tv', 'home') }}"
  #       friendly_name: 'Sharp TV'
  #       device_class: connectivity
  #       icon_template: mdi:television-box
  #     sonyps4:
  #       value_template: "{{ is_state('device_tracker.ps4', 'home') }}"
  #       friendly_name: 'PS4 Console'
  #       device_class: connectivity
  #       icon_template: mdi:playstation

####################################################
#                                                  #
#                Binary Sensor - Appliance         #
#                                                  #
####################################################

  - platform: template
    sensors:
      app_system:
        value_template: "{{ is_state('binary_sensor.samwash', 'on') and is_state('binary_sensor.samdry', 'on') }}"
        friendly_name: 'Appliances'
        device_class: connectivity
        icon_template: mdi:dishwasher
      samwash:
        value_template: "{{ is_state('device_tracker.samsung_washer', 'home') }}"
        friendly_name: 'Washing Machine'
        device_class: connectivity
        icon_template: mdi:washing-machine
      samdry:
        value_template: "{{ is_state('device_tracker.samsung_dryer', 'home') }}"
        friendly_name: 'Clothes Dryer'
        device_class: connectivity
        icon_template: mdi:tumble-dryer
      

####################################################
#                                                  #
#                Binary Sensor - HomeTabs          #
#                                                  #
####################################################


  # - platform: template
  #   sensors:
  #     ht_kitchen:
  #       value_template: "{{ is_state('device_tracker.kitchen_surface', 'home') }}"
  #       friendly_name: 'Kitchen'
  #       device_class: connectivity
  #       icon_template: mdi:fridge-outline
  #     ht_hall:
  #       value_template: "{{ is_state('device_tracker.hometab_hall', 'home') }}"
  #       friendly_name: 'Back Hall'
  #       device_class: connectivity
  #       icon_template: mdi:door-closed
      
      

