#################################################################
#                                                               #
#                     Packages/Presence                         #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

group:
  presence_e:
    name: Presence Entities
    entities:
      - binary_sensor.presence_away
      - binary_sensor.presence_home
      - binary_sensor.presence_allhome
      - input_boolean.presence_away
      - input_boolean.presence_guest
      - input_boolean.presence_party
      - input_select.presence_mode
      - binary_sensor.home_meg
      - binary_sensor.home_simon
      - binary_sensor.home_staci
      - binary_sensor.home_delia
      - input_boolean.away_simon
      - input_boolean.away_megan
      - input_boolean.away_staci
      - input_boolean.away_delia
      

  family: #used in presence automation below
    name: Family
    entities:
      - person.simon
      - person.megan
      - person.staci
      - person.delia
    
  people_e:
    name: People
    entities:
      - person.simon
      - person.megan
      - person.staci
      - person.delia
      - device_tracker.sphone_net
      - device_tracker.mphone_net
      - device_tracker.stphone_net
      - device_tracker.dphone_net

      
#################################################################
#                                                               #
#                       Binary Sensors                          #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#            Binary Sensors -          #
#                                                  #
#################################################### 

  - platform: template
    sensors:
      presence_away:
        friendly_name: Away
        value_template: "{{ is_state('input_select.presence_mode', 'All Away') }}"
        icon_template: mdi:account-off
        device_class: sound
      presence_home:
        friendly_name: Home
        value_template: "{{ is_state('binary_sensor.presence_away', 'off') }}"
        icon_template: mdi:account
        device_class: connectivity
      presence_allhome:
        friendly_name: All Home
        value_template: "{{ is_state('input_select.presence_mode', 'All Home') }}"
        icon_template: mdi:account
        device_class: connectivity
      home_meg:
        friendly_name: Meg Home
        value_template: "{{ is_state('person.megan', 'home') }}"
        icon_template: mdi:account
        device_class: connectivity
      home_simon:
        friendly_name: Simon Home
        value_template: "{{ is_state('person.simon', 'home') }}"
        icon_template: mdi:account
        device_class: connectivity
      home_staci:
        friendly_name: Staci Home
        value_template: "{{ is_state('person.staci', 'home') }}"
        icon_template: mdi:account
        device_class: connectivity
      home_delia:
        friendly_name: Delia Home
        value_template: "{{ is_state('person.delia', 'home') }}"
        icon_template: mdi:account
        device_class: connectivity

#################################################################
#                                                               #
#                       Input Boolean                           #
#                                                               #
#################################################################

input_boolean:

####################################################
#                                                  #
#            Input Boolean - presence Modes        #
#                                                  #
#################################################### 

  presence_away:
    name: Someone away for the night
    initial: off
    icon: mdi:account-remove

  presence_guest:
    name: Guest visiting (Someone home)
    initial: off
    icon: mdi:account-star

  presence_party:
    name: Party Mode (manual control)
    icon: mdi:ballon

  away_simon:
    name: Simon away

  away_megan:
    name: Megan away

  away_staci:
    name: Staci away

  away_delia:
    name: Delia away

#################################################################
#                                                               #
#                       Input Select                            #
#                                                               #
#################################################################

input_select:

####################################################
#                                                  #
#            Input Select - presence Modes         #
#                                                  #
#################################################### 

  presence_mode:
    name: Presence Mode
    options:
      - All Away
      - Someone Home
      - All Home
    #initial: All Away
    icon: mdi:account-location

#################################################################
#                                                               #
#                       Automation                              #
#                                                               #
#################################################################

# please see automation/house_mode.yaml


      