#################################################################
#                                                               #
#                     Packages/Printer                          #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

group:
  printer_e:
    name: Printer Entities
    entities:
      - binary_sensor.ink_black_alert
      - binary_sensor.ink_cyan_alert
      - binary_sensor.ink_magenta_alert
      - binary_sensor.ink_yellow_alert
      - input_number.ink_alert
      - input_boolean.ink_notify_system

  dishwasher_e:
    name: Dishwasher Entities
    entities:
      - input_boolean.dishwasher_notify_system
  

#################################################################
#                                                               #
#                       Binary Sensors                          #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#            Binary Sensors - Ink levels           #
#                                                  #
#################################################### 

  - platform: template
    sensors:
      ink_black_alert:
        friendly_name: Black Ink Alert
        value_template: "{{ float(states('sensor.epson_ink_level_black'), default=0) < float(states('input_number.ink_alert'), default=0) }}"
        icon_template: mdi:cup-water
      ink_cyan_alert:
        friendly_name: Cyan Ink Alert
        value_template: "{{ float(states('sensor.epson_ink_level_cyan'), default=0) < float(states('input_number.ink_alert'), default=0) }}"
        icon_template: mdi:cup-water
      ink_magenta_alert:
        friendly_name: Magenta Ink Alert
        value_template: "{{ float(states('sensor.epson_ink_level_magenta'), default=0) < float(states('input_number.ink_alert'), default=0) }}"
        icon_template: mdi:cup-water
      ink_yellow_alert:
        friendly_name: Yellow Ink Alert
        value_template: "{{ float(states('sensor.epson_ink_level_yellow'), default=0) < float(states('input_number.ink_alert'), default=0) }}"
        icon_template: mdi:cup-water

#################################################################
#                                                               #
#                       Input Boolean                           #
#                                                               #
#################################################################

input_boolean:

####################################################
#                                                  #
#            Input Boolean - Ink Notify system     #
#                                                  #
#################################################### 

  ink_notify_system:
    name: Printer Ink Message
    initial: off
    icon: mdi:printer-alert
  
  dishwasher_notify_system:
    name: Dishwasher Finished Message
    initial: off
    icon: mdi:dishwasher-alert

#################################################################
#                                                               #
#                       Input Number                            #
#                                                               #
#################################################################

input_number:

####################################################
#                                                  #
#                Input Numbers - ink message       #
#                                                  #
####################################################

  ink_alert:
    min: 0
    max: 100
    name: 'Ink Notify at'
    #initial: 20
    unit_of_measurement: '%'
    icon: mdi:alarm-bell


#################################################################
#                                                               #
#                       Automation                              #
#                                                               #
#################################################################

# please see appdaemon

  