#################################################################
#                                                               #
#                     Packages/Motion                           #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

group:
  motion_e:
    name: Motion Entities
    entities:
      - timer.bathroom_timer
      - timer.ensuite_timer
      - timer.laundry_timer
      - timer.garage_timer
      - timer.toilet_timer
      - input_select.bshower
      - input_select.eshower
      - input_select.lon
      - input_select.gon
      - input_select.ton
      - input_boolean.motion_in_bathroom
      - input_boolean.motion_in_laundry
      - input_boolean.motion_in_garage
      - input_boolean.motion_in_ensuite
      - input_boolean.motion_in_toilet
      # smartthings motion sensors
      - binary_sensor.toilet_motion_motion
      - binary_sensor.bathroom_motion_motion
      # rest sensors
      #- sensor.bathroom_motion
      - sensor.ensuite_motion
      - sensor.garage_motion
      - sensor.laundry_motion
      - sensor.bathroom_lux
      - sensor.ensuite_lux
      - sensor.garage_lux
      - sensor.laundry_lux
      #- sensor.bathroom_temperature
      - sensor.ensuite_temperature
      - sensor.garage_temperature
      - sensor.laundry_temperature
      # custom hue motion sensors 
      #- sensor.bathroom_sensor_light_level
      #- binary_sensor.bathroom_sensor_motion
      #- sensor.ensuite_sensor_light_level
      #- binary_sensor.ensuite_sensor_motion
      #- sensor.laundry_sensor_light_level
      #- binary_sensor.laundry_sensor_motion
      #- sensor.garage_sensor_light_level
      #- binary_sensor.garage_sensor_motion
      
      

  motion_a:
    name: Motion Automations
    entities:
      - automation.mode_set_bathroom_motion_off
      - automation.mode_set_bathroom_on
      - automation.mode_set_toilet_motion_off
      - automation.mode_set_toilet_on
      - automation.mode_set_ensuite_motion_off
      - automation.mode_set_ensuite_on
      - automation.mode_set_garage_motion_off
      - automation.mode_set_garage_on
      - automation.mode_set_laundry_motion_off
      - automation.mode_set_laundry_on
      
      
#################################################################
#                                                               #
#                       rest sensors                            #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#               rest motion sensors                #
#                                                  #
####################################################

  #bathroom
  # - platform: rest
  #   resource: !secret hue_bth_lux
  #   value_template: '{{ value_json.state.lightlevel }}'
  #   unit_of_measurement: Lux
  #   name: 'Bathroom Lux'
      
  # - platform: rest
  #   resource: !secret hue_bth_temp
  #   value_template: '{{ value_json.state.temperature | round(-1) | float / 100 }}'
  #   unit_of_measurement: 째C
  #   name: 'Bathroom Temperature'

  # - platform: rest
  #   resource: !secret hue_bth_motion
  #   value_template: '{{ value_json.state.presence }}'
  #   scan_interval: 2
  #   name: 'Bathroom Motion'


  #ensuite
  - platform: rest
    resource: !secret hue_ens_lux
    value_template: '{{ value_json.state.lightlevel }}'
    unit_of_measurement: Lux
    name: 'Ensuite Lux'

  - platform: rest
    resource: !secret hue_ens_temp
    value_template: '{{ value_json.state.temperature | round(-1) | float / 100 | float(default=0) }}'
    unit_of_measurement: 째C
    name: 'Ensuite Temperature'

  - platform: rest
    resource: !secret hue_ens_motion
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 2
    name: 'Ensuite Motion'



  #laundry
  - platform: rest
    resource: !secret hue_lnd_lux
    value_template: '{{ value_json.state.lightlevel }}'
    unit_of_measurement: Lux
    name: 'Laundry Lux'

  - platform: rest
    resource: !secret hue_lnd_temp
    value_template: '{{ value_json.state.temperature | round(-1) | float / 100 | float(default=0) }}'
    unit_of_measurement: 째C
    name: 'Laundry Temperature'

  - platform: rest
    resource: !secret hue_lnd_motion
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 2
    name: 'Laundry Motion'


  #garage
  - platform: rest
    resource: !secret hue_gar_lux
    value_template: '{{ value_json.state.lightlevel }}'
    unit_of_measurement: Lux
    name: 'Garage Lux'

  - platform: rest
    resource: !secret hue_gar_temp
    value_template: '{{ value_json.state.temperature | round(-1) | float / 100 | float(default=0) }}'
    unit_of_measurement: 째C
    name: 'Garage Temperature'

  - platform: rest
    resource: !secret hue_gar_motion
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 2
    name: 'Garage Motion'




#################################################################
#                                                               #
#                       Timer                                   #
#                                                               #
#################################################################

timer:

####################################################
#                                                  #
#            Timer - Motion Light Timers           #
#                                                  #
#################################################### 

  bathroom_timer:
    duration: '00:05:00'

  ensuite_timer:
    duration: '00:05:00'

  laundry_timer:
    duration: '00:00:20'

  garage_timer:
    duration: '00:05:00'

  toilet_timer:
    duration: '00:05:00'

#################################################################
#                                                               #
#                       Input Boolean                           #
#                                                               #
#################################################################

input_boolean:

####################################################
#                                                  #
#            Input Boolean - motion sensors        #
#                                                  #
#################################################### 

  motion_in_bathroom:
      name: Motion in the bathroom
      initial: off
      icon: mdi:run

  motion_in_laundry:
      name: Motion in the Laundry
      initial: off
      icon: mdi:run

  motion_in_garage:
      name: Motion in the Garage
      initial: off
      icon: mdi:run

  motion_in_ensuite:
      name: Motion in the Ensuite
      initial: off
      icon: mdi:run

  motion_in_toilet:
      name: Motion in the Toilet
      initial: off
      icon: mdi:run


#################################################################
#                                                               #
#                       Input Select                            #
#                                                               #
#################################################################

input_select:

####################################################
#                                                  #
#                Input Select - motion light mode  #
#                                                  #
####################################################

  bshower:
    name: Bathroom Mode
    options:
      - Motion
      - Bathroom On
      - Bathroom Off
    initial: Motion
    icon: mdi:vanish

  eshower:
    name: Ensuite Mode
    options:
      - Motion
      - Ensuite On
      - Ensuite Off
    initial: Motion
    icon: mdi:vanish

  lon:
    name: Laundry Mode
    options:
      - Motion
      - Laundry On
      - Laundry Off
    initial: Motion
    icon: mdi:vanish

  gon:
    name: Garage Mode
    options:
      - Motion
      - Garage On
      - Garage Off
    initial: Motion
    icon: mdi:vanish

  ton:
    name: Toilet Mode
    options:
      - Motion
      - Toilet On
      - Toilet Off
    initial: Motion
    icon: mdi:vanish


#################################################################
#                                                               #
#                       Automation                              #
#                                                               #
#################################################################

# please see nodered

automation:

#################################################################
#                                                               #
#                       Automation  for on/off of motion setting #
#                                                               #
#################################################################

  ###################################
  ##  bathroom Mode control
  ###################################

  - alias: mode_set_bathroom_motion_off
    trigger:
      - platform: state
        entity_id: input_select.bshower
        to: 'Motion'
      - platform: state
        entity_id: input_select.bshower
        to: 'Bathroom Off'
    action:
      - service: light.turn_off
        entity_id: light.bathroom

  - alias: mode_set_bathroom_on
    trigger:
      - platform: state
        entity_id: input_select.bshower
        to: 'Bathroom On'
    action:
      - service: light.turn_on
        entity_id: light.bathroom

  ###################################
  ##  toilet Mode control
  ###################################

  - alias: mode_set_toilet_motion_off
    trigger:
      - platform: state
        entity_id: input_select.ton
        to: 'Motion'
      - platform: state
        entity_id: input_select.ton
        to: 'Toilet Off'
    action:
      - service: light.turn_off
        entity_id: light.toilet

  - alias: mode_set_toilet_on
    trigger:
      - platform: state
        entity_id: input_select.ton
        to: 'Toilet On'
    action:
      - service: light.turn_on
        entity_id: light.toilet

  ###################################
  ##  ensuite Mode control
  ###################################

  - alias: mode_set_ensuite_motion_off
    trigger:
      - platform: state
        entity_id: input_select.eshower
        to: 'Motion'
      - platform: state
        entity_id: input_select.eshower
        to: 'Ensuite Off'
    action:
      - service: light.turn_off
        entity_id: group.ensuite

  - alias: mode_set_ensuite_on
    trigger:
      - platform: state
        entity_id: input_select.eshower
        to: 'Ensuite On'
    action:
      - service: light.turn_on
        entity_id: group.ensuite

  ###################################
  ##  laundry Mode control
  ###################################

  - alias: mode_set_laundry_motion_off
    trigger:
      - platform: state
        entity_id: input_select.lon
        to: 'Motion'
      - platform: state
        entity_id: input_select.lon
        to: 'Laundry Off'
    action:
      - service: light.turn_off
        entity_id: light.laundry

  - alias: mode_set_laundry_on
    trigger:
      - platform: state
        entity_id: input_select.lon
        to: 'Laundry On'
    action:
      - service: light.turn_on
        entity_id: light.laundry

  ###################################
  ##  garage Mode control
  ###################################

  - alias: mode_set_garage_motion_off
    trigger:
      - platform: state
        entity_id: input_select.gon
        to: 'Motion'
      - platform: state
        entity_id: input_select.gon
        to: 'Garage Off'
    action:
      - service: light.turn_off
        entity_id: light.garage

  - alias: mode_set_garage_on
    trigger:
      - platform: state
        entity_id: input_select.gon
        to: 'Garage On'
    action:
      - service: light.turn_on
        entity_id: light.garage

