#################################################################
#                                                               #
#                     Packages/Remote Control                   #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

group:
  remote_control_e:
    name: Remote Control Entities
    entities:
      - remote.harmony_hub
      - input_select.harmony
      - input_select.channel
      - binary_sensor.tv_on
      - binary_sensor.tv_off

  remote_control_a:
    name: Remote Control Automations
    entities:
      - automation.harmony_state_change
      - automation.harmony_activity_select
      - automation.harmony_tv_off_lightstrip_off
      - automation.harmony_tv_on_lightstrip_on

#################################################################
#                                                               #
#                       Input Select                            #
#                                                               #
#################################################################

input_select:

####################################################
#                                                  #
#            input_select harmony remote           #
#                                                  #
#################################################### 

  harmony:
    name: Harmony Control
    options:
      - Watch Chromecast
      - Listen to Music
      - Watch Fetch TV
      - PowerOff
    #initial: PowerOff
    icon: mdi:monitor

  channel:
    name: TV Channel
    options:
      - None
      - SBS
      - 7mate
      - ESPN  
    initial: None
    icon: mdi:television

#################################################################
#                                                               #
#                       Binary Sensor                           #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#                Binary Sensor - interface         #
#                                                  #
####################################################

  - platform: template
    sensors:
      tv_off:
        friendly_name: TV Off
        value_template: "{{ is_state('input_select.harmony', 'PowerOff') }}"
        icon_template: mdi:television-off
        device_class: motion
      tv_on:
        friendly_name: TV On
        value_template: "{{ is_state('binary_sensor.tv_off', 'off') }}"
        icon_template: mdi:television

#################################################################
#                                                               #
#                       Automation                              #
#                                                               #
#################################################################

automation:

####################################################
#                                                  #
#            automation - receiving webhooks       #
#                                                  #
#################################################### 


  #update the input select based upon someone using the remote
  - alias: harmony_state_change
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.harmony
          option: '{{ trigger.to_state.attributes.current_activity }}' 

  # using the input select        
  - alias: harmony_activity_select
    trigger:
      platform: state
      entity_id: input_select.harmony
    action:
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data_template:
          activity: >
            {% if is_state("input_select.harmony", "Watch Chromecast") %}
              28293288
            {% elif is_state("input_select.harmony", "Listen to Music") %}
              49478140
            {% elif is_state("input_select.harmony", "Watch Fetch TV") %}
              49478152
            {% else %}
              -1
            {% endif %}

  #turn on the light when the tv gets turned on (evening or night)
  - alias: harmony_tv_on_lightstrip_on
    trigger:
      - platform: state
        entity_id: input_select.harmony
        to: 'Watch Chromecast'
      - platform: state
        entity_id: input_select.harmony
        to: 'Listen to Music'
      - platform: state
        entity_id: input_select.harmony
        to: 'Watch Fetch TV'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.time_mode
          state: 'Evening'
        - condition: state
          entity_id: input_select.time_mode
          state: 'Late'
        - condition: state
          entity_id: input_select.time_mode
          state: 'Night'
    action:
      - service: light.turn_on
        entity_id: 
          - light.lounge_lightstrip 