# #################################################################
# #                                                               #
# #                     Packages/Climate                          #
# #                                                               #
# #################################################################

# #################################################################
# #                                                               #
# #                       Group                                   #
# #                                                               #
# #################################################################

# group:
#   climate_e:
#     name: Climate Entities
#     entities:
#       - binary_sensor.cc_ac_off      
#       - binary_sensor.cc_ac_fan
#       - binary_sensor.cc_ac_cool_ext
#       - binary_sensor.cc_ac_cool_int
#       - binary_sensor.cc_ac_cool_opt
#       - binary_sensor.cc_ac_heat_ext
#       - binary_sensor.cc_ac_heat_int
#       - binary_sensor.cc_ac_heat_opt
#       - binary_sensor.climate_optimal
#       # internal temps
#       - sensor.back_door_state_temperature_measurement
#       - sensor.front_door_state_temperature_measurement
#       - sensor.toilet_motion_temperature_measurement
#       - sensor.bathroom_sensor_temperature
#       - sensor.ensuite_sensor_temperature
#       - sensor.laundry_sensor_temperature
#       - sensor.garage_sensor_temperature
      
     

#################################################################
#                                                               #
#                            Binary Sensor                      #
#                                                               #
################################################################

binary_sensor:

    - platform: template
      sensors:
      # the internal temp is between optimal low and internal high
         climate_optimal:
            friendly_name: Pleasant
            value_template: "{{ (states('sensor.inside_now')|float >= states('input_number.cc_optlow')|float) and (states('sensor.inside_now')|float <= states('input_number.cc_inthigh')|float) }}"
            icon_template: mdi:emoticon-happy-outline
      

         cc_ac_manual_on:
            friendly_name: AC Manual
            value_template: "{{ (states('input_boolean.cc_ac_manual') == 'on') }}"
            icon_template: mdi:crosshairs-question      
         cc_ac_manual_off:
            friendly_name: AC Auto
            value_template: "{{ (states('input_boolean.cc_ac_manual') == 'off') }}"
            icon_template: mdi:fan-auto      
         
         cc_ac_off:
            friendly_name: AC Off
            value_template: "{{ (states('climate.rushbrook_aircon') == 'off') }}"
            icon_template: mdi:hvac-off      
         cc_ac_fan:
            friendly_name: AC Fan
            value_template: "{{ (states('climate.rushbrook_aircon') == 'fan_only') }}"
            icon_template: mdi:air-conditioner
         cc_ac_cool_ext:
            friendly_name: AC Cool (Ext)
            value_template: "{{ (states('climate.rushbrook_aircon') == 'cool') and (state_attr('climate.rushbrook_aircon', 'temperature')|float == states('input_number.cc_exthigh')|float) }}"
            icon_template: mdi:arrow-collapse-down
         cc_ac_cool_int:
            friendly_name: AC Cool (Int)
            value_template: "{{ (states('climate.rushbrook_aircon') == 'cool') and (state_attr('climate.rushbrook_aircon', 'temperature')|float == states('input_number.cc_inthigh')|float) }}"
            icon_template: mdi:arrow-expand-down
         cc_ac_cool_opt:
            friendly_name: AC Cool (Opt)
            value_template: "{{ (states('climate.rushbrook_aircon') == 'cool') and (state_attr('climate.rushbrook_aircon', 'temperature')|float == states('input_number.cc_opthigh')|float) }}"
            icon_template: mdi:arrow-collapse-vertical
         cc_ac_heat_ext:
            friendly_name: AC Heat (Ext)
            value_template: "{{ (states('climate.rushbrook_aircon') == 'heat') and (state_attr('climate.rushbrook_aircon', 'temperature')|float == states('input_number.cc_extlow')|float) }}"
            icon_template: mdi:arrow-collapse-up
         cc_ac_heat_int:
            friendly_name: AC Heat (Int)
            value_template: "{{ (states('climate.rushbrook_aircon') == 'heat') and (state_attr('climate.rushbrook_aircon', 'temperature')|float == states('input_number.cc_intlow')|float) }}"
            icon_template: mdi:arrow-expand-up
         cc_ac_heat_opt:
            friendly_name: AC Heat (Opt)
            value_template: "{{ (states('climate.rushbrook_aircon') == 'heat') and (state_attr('climate.rushbrook_aircon', 'temperature')|float == states('input_number.cc_optlow')|float) }}"
            icon_template: mdi:arrow-collapse-vertical
      
