#################################################################
#                                                               #
#                     Packages/Climate                          #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

group:
  climate_e:
    name: Climate Entities
    entities:
      - input_number.temp_opt_high
      - input_number.temp_opt_low
      - input_number.temp_int_high
      - input_number.temp_int_low
      - input_number.temp_ext_high
      - input_number.temp_ext_low
      - binary_sensor.climate_warn_hot
      - binary_sensor.climate_warn_hot_overnight
      - binary_sensor.climate_warn_cold
      - binary_sensor.climate_warn_cold_overday
      - binary_sensor.climate_hot_turn_on_cooling
      - binary_sensor.climate_opt_turn_off_warming
      - binary_sensor.climate_opt_turn_off_cooling
      - binary_sensor.climate_cold_turn_on_warming
      - binary_sensor.climate_optimal
      - binary_sensor.climate_hot_outside_on_fan
      - binary_sensor.climate_cool_outside_off_fan
      # internal temps
      - sensor.back_door_state_temperature_measurement
      - sensor.front_door_state_temperature_measurement
      - sensor.toilet_motion_temperature_measurement
      - sensor.bathroom_sensor_temperature
      - sensor.ensuite_sensor_temperature
      - sensor.laundry_sensor_temperature
      - sensor.garage_sensor_temperature
      
      
#################################################################
#                                                               #
#                            Input Number                       #
#                                                               #
#################################################################

input_number:

####################################################
#                                                  #
#                climate ranges                    #
#                                                  #
####################################################

  temp_opt_high:
    min: 21
    max: 22
    name: 'Optimal (high)'
    unit_of_measurement: 'C'
    icon: mdi:arrow-expand-vertical

  temp_opt_low:
    min: 20
    max: 21
    name: 'Optimal (low)'
    unit_of_measurement: 'C'
    icon: mdi:arrow-collapse-vertical

  temp_int_high:
    min: 22
    max: 24
    name: 'Internal High (prefer)'
    unit_of_measurement: 'C'
    icon: mdi:arrow-collapse-up

  temp_int_low:
    min: 18
    max: 20
    name: 'Internal Low (prefer)'
    unit_of_measurement: 'C'
    icon: mdi:arrow-collapse-down

  temp_ext_high:
    min: 26
    max: 30
    name: 'External High (Warn)'
    unit_of_measurement: 'C'
    icon: mdi:fire

  temp_ext_low:
    min: 12
    max: 16
    name: 'External Low (Warn)'
    unit_of_measurement: 'C'
    icon: mdi:snowflake


#################################################################
#                                                               #
#                            Binary Sensor                      #
#                                                               #
#################################################################

binary_sensor:

  - platform: template
    sensors:
      # todays high is higher than our hot, and the internal temp is higher than optimal and it is before evening
      climate_warn_hot:
        friendly_name: Hot Day
        value_template: "{{ (states('sensor.dark_sky_daytime_high_temperature_0d')|float > states('input_number.temp_ext_high')|float) and (states('sensor.inside_now')|float > states('input_number.temp_opt_high')|float) and (now().hour < 17) }}"
        icon_template: mdi:air-conditioner
        device_class: heat
      # todays low is higher than our optimal, and the internal temp is higher than optimal and it is after evening
      climate_warn_hot_overnight:
        friendly_name: Hot Night
        value_template: "{{ (states('sensor.dark_sky_overnight_low_temperature_0d')|float > states('input_number.temp_opt_high')|float) and (states('sensor.inside_now')|float > states('input_number.temp_opt_high')|float) and (now().hour > 17) }}"
        icon_template: mdi:air-conditioner
        device_class: heat
      # todays low is lower than our cold, and the internal temp is lower than optimal and it is after evening
      climate_warn_cold:
        friendly_name: Cold Night
        value_template: "{{ (states('sensor.dark_sky_overnight_low_temperature_0d')|float < states('input_number.temp_ext_low')|float) and (states('sensor.inside_now')|float < states('input_number.temp_opt_low')|float) and (now().hour > 17) }}"
        icon_template: mdi:radiator
        device_class: cold
      # todays hign is lower than our optimal, and the internal temp is lower than optimal and it is before evening
      climate_warn_cold_overday:
        friendly_name: Cold Day
        value_template: "{{ (states('sensor.dark_sky_daytime_high_temperature_0d')|float < states('input_number.temp_opt_low')|float) and (states('sensor.inside_now')|float < states('input_number.temp_opt_low')|float) and (now().hour < 17) }}"
        icon_template: mdi:radiator
        device_class: cold

      # the internal temp is higher than internal high preference
      climate_hot_turn_on_cooling:
        friendly_name: Hot Now
        value_template: "{{ (states('sensor.inside_now')|float > states('input_number.temp_int_high')|float) }}"
        icon_template: mdi:air-conditioner
        device_class: heat
      # the internal temp is lower than internal low preference
      climate_cold_turn_on_warming:
        friendly_name: Cold Now
        value_template: "{{ (states('sensor.inside_now')|float < states('input_number.temp_int_low')|float) }}"
        icon_template: mdi:radiator
        device_class: cold

      # the internal temp is lower than internal optimal high 
      climate_opt_turn_off_cooling:
        friendly_name: Cooling
        value_template: "{{ (states('sensor.inside_now')|float <= states('input_number.temp_opt_high')|float) }}"
        icon_template: mdi:fan-off
        device_class: sound
      # the internal temp is higher than internal optimal low
      climate_opt_turn_off_warming:
        friendly_name: Warming
        value_template: "{{ (states('sensor.inside_now')|float >= states('input_number.temp_opt_low')|float) }}"
        icon_template: mdi:radiator-off
        device_class: sound

      # the internal temp is between optimals
      climate_optimal:
        friendly_name: Pleasant
        value_template: "{{ (states('sensor.inside_now')|float >= states('input_number.temp_int_low')|float) and (states('sensor.inside_now')|float <= states('input_number.temp_int_high')|float) }}"
        icon_template: mdi:emoticon-happy-outline
      
      # for the fans
      # the internal temp is higher than the internal low preference and the current outside temp is higher than the optimal high
      climate_hot_outside_on_fan:
        friendly_name: Fans
        value_template: "{{ (states('sensor.inside_now')|float >= states('input_number.temp_int_low')|float) and (states('sensor.bom_tuggeranong_isabella_plains_aws_feels_like_c')|float >= states('input_number.temp_opt_high')|float) }}"
        icon_template: mdi:fan
      # the internal temp is lower than the internal optimal high and the current outside temp is lower than the internal high preference
      climate_cool_outside_off_fan:
        friendly_name: Fans
        value_template: "{{ (states('sensor.inside_now')|float <= states('input_number.temp_opt_high')|float) and (states('sensor.bom_tuggeranong_isabella_plains_aws_feels_like_c')|float <= states('input_number.temp_int_high')|float) }}"
        icon_template: mdi:fan-off
        device_class: sound

      
