#################################################################
#                                                               #
#                     Packages/Car Times                        #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                     Traccar                         #
#                                                               #
#################################################################


# Example configuration.yaml entry
device_tracker:
  - platform: traccar
    host: localhost
    port: 18683
    ssl: false
    verify_ssl: false
    username: !secret traccar_user
    password: !secret traccar_pass
    event: 
      - 'all_events'
    monitored_conditions: ['alarm', 'ignition', 'speed', 'total_distance']
    new_device_defaults:
      track_new_devices: true

#################################################################
#                                                               #
#                       Binary Sensors                          #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#            Binary Sensors - Car Connect          #
# Tasker sends to IFTTT                            #
# IFTTT sets this when bluetooth connects to the car
#                                                  #
#################################################### 

  - platform: template
    sensors:
      drive_meg:
        friendly_name: Meg Drive
        value_template: "{{ is_state('input_boolean.megan_outback', 'on') }}"
        icon_template: mdi:car
      drive_simon:
        friendly_name: Simon Drive
        value_template: "{{ is_state('input_boolean.simon_outback', 'on') }}"
        icon_template: mdi:car-key
      drive_staci: 
        friendly_name: Staci Drive
        value_template: "{{ is_state('input_boolean.staci_outback', 'on') }}"
        icon_template: mdi:car
      drive_delia: 
        friendly_name: Delia Drive
        value_template: "{{ is_state('input_boolean.delia_outback', 'on') }}"
        icon_template: mdi:car

#################################################################
#                                                               #
#                       Input Boolean                           #
#                                                               #
#################################################################

input_boolean:

####################################################
#                                                  #
#            Input Boolean - Car away              #
#                                                  #
#################################################### 

  presence_holiday:
    name: Car Away
    initial: off
    icon: mdi:airplane-takeoff

####################################################
#                                                  #
#            Input Boolean - Car connections       #
#                                                  #
#################################################### 

  outback_just:
    name: Someone has just connected to the outback
    icon: mdi:car-connected

  garage_just:
    name: Someone has just opened the garage
    icon: mdi:garage-alert

  simon_outback:
    name: Simon is connected to the Outback
    icon: mdi:car-connected

  megan_outback:
    name: Meg is connected to the Outback
    icon: mdi:car-connected

######### NOT USED - here for completeness

  staci_outback: #requires tasker - not being used
    name: Staci is connected to the Outback
    icon: mdi:car-connected
    
  delia_outback: #requires tasker - not being used
    name: Delia is connected to the Outback
    icon: mdi:car-connected

#################################################################
#                                                               #
#                       Timer                                   #
#                                                               #
#################################################################

timer: 

####################################################
#                                                  #
#           timer - car connect                    #
#                                                  #
#    don't open the door for the first 5 mins      #
#    don't open the door if you already have       #
####################################################   

  outback_just:
    duration: '00:05:00'

  garage_just:
    duration: '00:05:00'

#################################################################
#                                                               #
#                       Sensor                                  #
#                                                               #
#################################################################

sensor:

#################################################################
#                                                               #
#                     FUEL
#                                                               #
#################################################################

  - platform: nsw_fuel_station
    station_id: 18786
    fuel_types: ['E10', 'U91']
  - platform: nsw_fuel_station
    station_id: 18809
    fuel_types: ['P98']
   

####################################################
#                                                  #
#           sensor - geofence from traccar         #
#                                                  #
#################################################### 

  - platform: template
    sensors:
      geofence_outback:
        value_template: "{{ state_attr('device_tracker.outback', 'geofence') }}"
      geofence_rx8:
        value_template: "{{ state_attr('device_tracker.rx8', 'geofence') }}"
      blue_msam9:
        value_template: "{{ state_attr('sensor.mpixel_bluetooth_connection', 'connected_paired_devices') }}"
      blue_spixel:
        value_template: "{{ state_attr('sensor.spixel3_bluetooth_connection', 'connected_paired_devices') }}"
        #28:A1:83:8A:48:63 Outback 
        #F4:4E:FD:30:A8:28 RX8


#################################################################
#                                                               #
#                       Automation                              #
#                                                               #
#################################################################

# please see automation/house_mode.yaml
#['08:97:98:28:DB:03 (Julianna HR 0489)']
automation:

####################################################
#                                                  #
#           automation - car connect               #
#                                                  #
#    don't open the door for the first 5 mins      #
#                                                  #
#################################################### 

  # turn on flag when someone starts car 
  - alias: transport_car_connect_timer_start
    trigger:
      - platform: state
        entity_id: input_boolean.simon_outback
        to: 'on'
      - platform: state
        entity_id: input_boolean.megan_outback
        to: 'on'
      - platform: state
        entity_id: input_boolean.staci_outback
        to: 'on'
      - platform: state
        entity_id: input_boolean.delia_outback
        to: 'on'
    action:
      - service: timer.start
        entity_id: timer.outback_just
      - service: homeassistant.turn_on
        entity_id: input_boolean.outback_just

  # turn on flag when appdaemon opens the garage - node red will turn off
  - alias: transport_garage_open_timer_start
    trigger:
      - platform: state
        entity_id: input_boolean.garage_just
        to: 'on'
    action:
      - service: timer.start
        entity_id: timer.garage_just
      
