#################################################################
#                                                               #
#                     Packages/GPS                              #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Group                                   #
#                                                               #
#################################################################

group:
  gps_e:
    name: GPS Entities
    entities:
      - sensor.sphone_gps_up
      - sensor.mphone_gps_up
      - sensor.stphone_gps_up
      - sensor.dphone_gps_up
      - sensor.sphone_type
      - sensor.mphone_type
      - sensor.stphone_type
      - sensor.dphone_type


#################################################################
#                                                               #
#                   Input Boolean                              #
#                                                               #
#################################################################

input_boolean:

  button_pushed:
    name: GPS reset button
    initial: off
    icon: mdi:crosshairs-gps

#################################################################
#                                                               #
#                            Sensors                            #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                Last updated                      #
#                                                  #
####################################################

  - platform: template
    sensors:
      sphone_gps_up:
        friendly_name: Simon Phone GPS
        value_template: '{{ states.person.simon.last_updated }}'
      mphone_gps_up:
        friendly_name: Megan Phone GPS
        value_template: '{{ states.person.simon.last_updated }}'
      stphone_gps_up:
        friendly_name: Staci Phone GPS
        value_template: '{{ states.person.simon.last_updated }}'
      dphone_gps_up:
        friendly_name: Delia Phone GPS
        value_template: '{{ states.person.simon.last_updated }}'


      
