esphome:
  name: motiontest
  platform: ESP8266
  board: d1_mini
  arduino_version: recommended

wifi:
  ssid: BB8
  password: sCmtA9a7$
  #bssid: 78:D2:94:AA:52:44
  # ...
  #manual_ip:
    # Set this to the IP of the ESP
  #  static_ip: 10.0.0.75
    # Set this to the IP address of the router. Often ends with .1
  #  gateway: 10.0.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
  #  subnet: 255.255.255.0


# Enable logging
logger:
  level: ERROR
  
# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    name: Motion Test
    pin: D2
    device_class: motion
